### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by sushi2k** [sensepost/objection#1]
Hi, 

thanks for this amazing tool. When trying to "download" or "ios plist cat" a file I am only getting this error on iOS 10.3.1 (I write download, press space and then this error is triggered):

```
iPhone on (iPhone: 10.3.1) [usb] # download Exception in thread Thread-201:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/sven/virtual-python3/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 860, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/Users/sven/virtual-python3/lib/python3.6/site-packages/objection/console/completer.py", line 115, in get_completions
    meta = extra['meta'] if 'meta' in extra else None
TypeError: string indices must be integers
```

With Python 3.6.1
```
(virtual-python3) ➜  objection python -V
Python 3.6.1
```

**Comment by leonjza** [comment]
Thanks for the report! Looks like the tab completion fell over here.

Quick question, the file you tried to download/cat, was it in the current directory, or was it a file you were accessing in a relative path?

**Comment by leonjza** [comment]
Ive tagged and uploaded 0.0.2 to pypi, which includes the commit at 0781dc0. Could you update with `pip3 install objection --upgrade` and let me know if it happens again?

Thanks!

**Comment by sushi2k** [comment]
> Quick question, the file you tried to download/cat, was it in the current directory, or was it a file you were accessing in a relative path?

It was in the current directory. Didn't try it via a path.

I just updated to 0.0.2 and download is now working as a charm. Thanks for the quick fix 👍

**Comment by leonjza** [comment]
🎉
