### ISSUE TITLE
Error Installing objection on windows7

### ISSUE THREAD

**Issue by ajmalkhanjamro** [sensepost/objection#103]
hello iam getting error on windows 7 install object its getting failed to copy some tem files here are the logs 

```
  warnings.warn(msg)

error: can't copy '\TEMP\pip_build_Network Computers\objection\objection\hooks\android\device-information.js': doesn't exist or not a regular file

----------------------------------------
Cleaning up...
  Removing temporary dir C:\Windows\TEMP\pip_build_Network Computers...
Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Windows\\TEMP\\pip_build_Network Computers\\objection\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Windows\TEMP\pip-q200dg2f-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in C:\Windows\TEMP\pip_build_Network Computers\objection
Exception information:
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "C:\Python34\lib\site-packages\pip\commands\install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "C:\Python34\lib\site-packages\pip\req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "C:\Python34\lib\site-packages\pip\req.py", line 706, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "C:\Python34\lib\site-packages\pip\util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Windows\\TEMP\\pip_build_Network Computers\\objection\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Windows\TEMP\pip-q200dg2f-record\install-record.txt --single-version-externally-managed --compile failed with error code 1 in C:\Windows\TEMP\pip_build_Network Computers\objection
```

**Comment by leonjza** [comment]
Unfortunately Windows support is not great and I don't really know what could have caused the error you have. As a test, I installed objection (with `pip3 install objection`) in a Windows 10 VM running python 3.6.6 (Python 3.7 was not working for some reason) and it seems to work fine.

![](https://i.imgur.com/0ZHrMSM.png)

HTH
