### ISSUE TITLE
Error while patching

### ISSUE THREAD

**Issue by bikee1235** [sensepost/objection#105]
Hi,
I m getting an error while patching an IPA

```
**Pre-Test-Sub:Desktop radmin$ objection patchipa --source ~/Desktop/pcloudhelper.ipa  --codesign-signature KNHUXXXXXX**


A newer version of objection is available!
You have v1.2.9 and v1.4.1 is ready for download.

Upgrade with: pip3 install objection --upgrade
For more information, please see: https://github.com/sensepost/objection/wiki/Updating

Using latest Github gadget version: 12.0.3
Patcher will be using Gadget version: 12.0.3
No provision file specified, searching for one...
No provisioning files found. Please specify one or generate one by building an app.
Working with app: pcloudyhelper.app
Bundle identifier is: com.pcloudy.pcloudyhelper
Creating Frameworks directory for FridaGadget...
Codesigning 1 .dylib's with signature KNHU2BX5V9
Code signing: FridaGadget.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 207, in patchipa
    patch_ios_ipa(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 70, in patch_ios_ipa
    patcher.archive_and_codesign(original_name=source, codesign_signature=codesign_signature)
  File "/usr/local/lib/python3.6/site-packages/objection/utils/patchers/ios.py", line 405, in archive_and_codesign
    self.patched_ipa_path
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
Cleaning up temp files...



**Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/1r/zlmjmrz52x93ky7bccddxtgr0000gn/T/pcloudyhelper-frida-codesigned.ipa'**
```

Please help me in this 

What's need to changes

**Comment by leonjza** [comment]
Could you unzip the target IPA and check if there are any weird characters / odd spaces that may cause issues with the `applesign` command? The error seems to come from [here](https://github.com/sensepost/objection/blob/1.2.9/objection/utils/patchers/ios.py#L405) where the the `patched_ipa_path` is referenced.

This one is a little hard to debug for me without access to the IPA.

**Comment by rustymagnet3000** [comment]
Hey @bikee1235 

is the issue here? 
```
No provision file specified, searching for one...
No provisioning files found. Please specify one or generate one by building an app.
```

I always create an embedded.mobileprovision file with my device's UUID inside, with an empty xCode project.  Then add the following in your patchipa command:

` -p embedded.mobileprovision`

**Comment by leonjza** [comment]
Ah I missed that, good spot @rustymagnet3000 ! @bikee1235 The wiki contains a lot of documentation about the patching process for iOS [here](https://github.com/sensepost/objection/wiki/Patching-iOS-Applications).
