### ISSUE TITLE
Memory dump doesnt work shows error

### ISSUE THREAD

**Issue by chackokavanattu12** [sensepost/objection#107]
I am using objection 1.4.1 and used the memory dump all hello.txt 

After 4% i get the following 

```
on (google: 7.1.1) [usb] # memory dump all hello.txt
Destination file hello.txt already exists
Continue append? [y/N]: y
Will dump 789 rw- images, totalling 337.2 MiB
Dumping 8.0 MiB from base: 0x77bbc000  [#-----------------------------------]    4%  0d 00:02:01  


An exception occurred while processing the command. If this looks like a code related error, please file a bug report!
Error: Error: access violation accessing 0x7c090000
    at [anon] (script1.js:7)
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)
Traceback (most recent call last):
  File "/root/Objection/lib/python3.6/site-packages/objection/console/repl.py", line 389, in start_repl
    self.run_command(document)
  File "/root/Objection/lib/python3.6/site-packages/objection/console/repl.py", line 200, in run_command
    exec_method(arguments)
  File "/root/Objection/lib/python3.6/site-packages/objection/commands/memory.py", line 71, in dump_all
    dump = api.read_bytes(int(image['base'], 16), image['size'])
  File "/root/Objection/lib/python3.6/site-packages/frida/core.py", line 319, in method
    return script._rpc_request('call', js_name, args)
  File "/root/Objection/lib/python3.6/site-packages/frida/core.py", line 247, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: access violation accessing 0x7c090000
    at [anon] (script1.js:7)
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)
```

**Comment by leonjza** [comment]
Thanks for the report. After double checking that the size to dump calculation is correct we may need to wrap the dumper in a try catch to simply hop over the images that appear to no longer be readable.

**Comment by chackokavanattu12** [comment]
Thanks Leon, Please let me know when the bug has been fixed :)

**Comment by leonjza** [comment]
This will be fixed in the next release.
