### ISSUE TITLE
ValueError: I/O operation on closed file in `patchapk`

### ISSUE THREAD

**Issue by jazrak** [sensepost/objection#108]
```
j in ~/temp λ uname -a
Darwin MacBook-Air.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
```
See output for yourself:

```
j in ~/temp λ objection patchapk --source sc.apk                     
No architecture specified. Determining it using `adb`...

Detected target device architecture as: arm64-v8a

Using latest Github gadget version: 12.0.3
Patcher will be using Gadget version: 12.0.3

Unpacking sc.apk

Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    load_entry_point('objection==1.4.1', 'console_scripts', 'objection')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 244, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 153, in patch_android_apk
    patcher.inject_internet_permission()
  File "/usr/local/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 378, in inject_internet_permission
    if internet_permission in self._get_appt_output():
  File "/usr/local/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 256, in _get_appt_output
    if len(o.err) > 0:
  File "/usr/local/lib/python3.6/site-packages/delegator.py", line 114, in err
    self.__err = self.std_err.read()
ValueError: I/O operation on closed file.

Cleaning up temp files...

Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/ql/k3ys0l5x7276wsr8jl990t0h0000gn/T/tmpiwqdcg6t.apktemp.objection.apk'```

I noticed that the temp file is indeed missing, and only the file `1.apk` is actually present in temp folder `/var/folders/ql/k3ys0l5x7276wsr8jl990t0h0000gn/T/`.

**Comment by leonjza** [comment]
Do you have `aapt` available in `PATH`? The patcher is failing to get its output.

**Comment by RumoEL** [comment]
@leonjza  
output:
sudo objection patchapk --source Wifi_WPS_Plus_v3.3.1_apkpure.com.apk                 
Checking for a newer version of objection...
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 14.2.2
Remote FridaGadget version is v14.2.2, local is v0. Downloading...
Downloading from: https://github.com/frida/frida/releases/download/14.2.2/frida-gadget-14.2.2-android-arm64.so.xz
Downloading arm64-v8a library to /root/.objection/android/arm64-v8a/libfrida-gadget.so.xz...
Unpacking /root/.objection/android/arm64-v8a/libfrida-gadget.so.xz...
Cleaning up downloaded archives...
Patcher will be using Gadget version: 14.2.2
Traceback (most recent call last):
  File "/usr/bin/objection", line 33, in <module>
    sys.exit(load_entry_point('objection==1.9.6', 'console_scripts', 'objection')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/objection/console/cli.py", line 370, in patchapk
    patch_android_apk(**locals())
  File "/usr/lib/python3.9/site-packages/objection/commands/mobile_packages.py", line 182, in patch_android_apk
    if not patcher.is_apktool_ready():
  File "/usr/lib/python3.9/site-packages/objection/utils/patchers/android.py", line 225, in is_apktool_ready
    o = delegator.run(self.list2cmdline([
  File "/usr/lib/python3.9/site-packages/delegator.py", line 126, in out
    self.__out = self.std_out.read()
ValueError: I/O operation on closed file.
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpxt5c98py.apktemp.objection.apk'
[user@archlinux soft]$ whereis aapt
aapt: /home/user/Android/Sdk/build-tools/30.0.3/aapt

**Comment by Zproger** [comment]
```
>> objection patchapk -D -n --source test.apk

Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 15.2.2
Patcher will be using Gadget version: 15.2.2

App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...

Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Built new APK with injected loadLibrary and frida-gadget
Performing zipalign
Zipalign completed
Signing new APK.

Traceback (most recent call last):
  File "/home/user/.local/bin/objection", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/objection/console/cli.py", line 373, in patchapk
    patch_android_apk(**locals())
  File "/home/user/.local/lib/python3.10/site-packages/objection/commands/mobile_packages.py", line 223, in patch_android_apk
    patcher.sign_apk()
  File "/home/user/.local/lib/python3.10/site-packages/objection/utils/patchers/android.py", line 913, in sign_apk
    if len(o.err) > 0:
  File "/home/user/.local/lib/python3.10/site-packages/delegator.py", line 143, in err
    self.__err = self.std_err.read()
ValueError: I/O operation on closed file.
Cleaning up temp files...
```


**total:**
Writes to the file after it is closed. Using Python 3.10.4 and system: 5.15.32-1-MANJARO x86_64 GNU/Linux.
How can I fix this error now?
