### ISSUE TITLE
Android SSL verifyChain

### ISSUE THREAD

**Issue by merkader69** [sensepost/objection#117]
Android Version: 7.0.0
Emulator: Genymotion
OS: Windows 10

I'm trying to run an app with a proxy on, and have been stumped by this error: 

```
08-09 13:08:22.245   531   588 E SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
08-09 13:08:22.245   531   583 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
08-09 13:08:22.246   531   588 E SupplicantWifiScannerImpl: Failed to start scan, freqs={2412}
08-09 13:08:22.246   531   583 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
08-09 13:08:22.955  3499  3623 V a       : Sending swipe
08-09 13:08:23.031  3499  3536 I FirebasePerformance: Did not receive a HTTP Response Code
08-09 13:08:23.031  3499  3536 I FirebasePerformance: Unable to process an HTTP request/response due to missing or invalid values. See earlier log statements for additional information on the specific invalid/missing values.
08-09 13:08:23.032  3499  3603 E LogError: Server error - statusCode: 504, message: An error occurred, result: ssl
08-09 13:08:23.032  3499  3603 E LogError: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:302)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at co.yellw.data.api.b.a.intercept(ConnectivityInterceptor.kt:18)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at co.yellw.data.api.b.b.intercept(SecurityInterceptor.kt:82)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at co.yellw.data.api.b.c.intercept(UserAgentInterceptor.kt:30)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-09 13:08:23.032  3499  3603 E LogError:      at okhttp3.RealCall.execute(RealCall.java:77)
08-09 13:08:23.032  3499  3603 E LogError:      at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(Unknown Source)
08-09 13:08:23.032  3499  3603 E LogError:      at retrofit2.h.a(OkHttpCall.java:180)
08-09 13:08:23.032  3499  3603 E LogError:      at retrofit2.adapter.rxjava2.c.subscribeActual(CallExecuteObservable.java:42)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.Observable.subscribe(Observable.java:12036)
08-09 13:08:23.032  3499  3603 E LogError:      at retrofit2.adapter.rxjava2.a.subscribeActual(BodyObservable.java:34)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.Observable.subscribe(Observable.java:12036)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
08-09 13:08:23.032  3499  3603 E LogError:      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
08-09 13:08:23.032  3499  3603 E LogError:      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-09 13:08:23.032  3499  3603 E LogError:      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
08-09 13:08:23.032  3499  3603 E LogError:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-09 13:08:23.032  3499  3603 E LogError:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-09 13:08:23.032  3499  3603 E LogError:      at java.lang.Thread.run(Thread.java:761)
08-09 13:08:23.032  3499  3603 E LogError: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
08-09 13:08:23.032  3499  3603 E LogError:      at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
08-09 13:08:23.032  3499  3603 E LogError:      at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-09 13:08:23.032  3499  3603 E LogError:      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
08-09 13:08:23.032  3499  3603 E LogError:      ... 43 more
08-09 13:08:23.032  3499  3603 E LogError: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

I read through the sensepost blog, and also checked the code: 

https://github.com/sensepost/objection/blob/d53ff2c4dec31d3cf5ea6dd8c657e36777ad16da/objection/hooks/android/pinning/disable.js#L134-L181

On line 150 

TrustManagerImpl.verifyChain.implementation = function (untrustedChain, trustAnchorChain, host, clientAuth, ocspData, tlsSctData) {

I'm not very smart with java code nor very knowledgeable whatsoever with the reverse engineering of it so I apologize if I am overlooking something excruciatingly obvious, but based on my logcat it appears that I don't have verifyChain flare up as a culprit, is there something I'm doing wrong or is it just the way this app functions? Thanks!

**Comment by leonjza** [comment]
Given the exception thrown, did you apply the hook (`android sslpinning disable`) before making API requests?
