### ISSUE TITLE
patch apk fails

### ISSUE THREAD

**Issue by mehhrad** [sensepost/objection#122]
i tried this command to embed frida to some apk ... all of them failed with the same error

```
 objection patchapk -s foursquare-11-9-1.apk 
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 12.0.8
Patcher will be using Gadget version: 12.0.8
Unpacking foursquare-11-9-1.apk
An error may have occured while extracting the APK.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/btn_liked_off.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/pull_to_refresh_on_map_bg.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/abs__dialog_full_holo_dark.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/abs__dialog_full_holo_light.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/btn_liked_off.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/abs__dialog_full_holo_dark.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/abs__dialog_full_holo_light.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/abs__dialog_full_holo_light.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/abs__dialog_full_holo_dark.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-mdpi-v4/btn_not_liked_off.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/btn_not_liked_off.9.png". Renaming it to *.png.
S: Could not decode file, replacing by FALSE value: raw/keep.xml
W: Cant find 9patch chunk in file: "drawable-hdpi-v4/btn_not_liked_off.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "drawable-xhdpi-v4/btn_liked_off.9.png". Renaming it to *.png.

App already has android.permission.INTERNET
Reading smali from: /tmp/tmpj_y1o4j0.apktemp/smali/com/joelapenna/foursquared/MainActivity.smali
Injecting into an existing constructor
Injecting loadLibrary call at line: 68
Writing patched smali back to: /tmp/tmpj_y1o4j0.apktemp/smali/com/joelapenna/foursquared/MainActivity.smali
Creating library path: /tmp/tmpj_y1o4j0.apktemp/lib/armeabi-v7a
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

W: res/drawable-v21/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable-v21/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: A/        ( 3643): First type is not attr!
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 2018072022, --version-name, 11.9.1, --no-version-vectors, -F, /tmp/APKTOOL10898425281174132023.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/semycolon/.local/share/apktool/framework/1.apk, -S, /tmp/tmpj_y1o4j0.apktemp/res, -M, /tmp/tmpj_y1o4j0.apktemp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 2018072022, --version-name, 11.9.1, --no-version-vectors, -F, /tmp/APKTOOL10898425281174132023.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/semycolon/.local/share/apktool/framework/1.apk, -S, /tmp/tmpj_y1o4j0.apktemp/res, -M, /tmp/tmpj_y1o4j0.apktemp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 134): [/usr/bin/aapt, p, --min-sdk-version, 16, --target-sdk-version, 23, --version-code, 2018072022, --version-name, 11.9.1, --no-version-vectors, -F, /tmp/APKTOOL10898425281174132023.tmp, -0, arsc, -0, webp, -0, arsc, -I, /home/semycolon/.local/share/apktool/framework/1.apk, -S, /tmp/tmpj_y1o4j0.apktemp/res, -M, /tmp/tmpj_y1o4j0.apktemp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signing the new APK may have failed.
jarsigner: unable to open jar file: /tmp/tmpj_y1o4j0.apktemp.objection.apk


Signed the new APK
Performing zipalign
Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error: 

Unable to open '/tmp/tmpj_y1o4j0.apktemp.objection.apk' as zip archive

Zipaling completed
Copying final apk from /tmp/tmpj_y1o4j0.apktemp.aligned.objection.apk to foursquare-11-9-1.objection.apk in current directory...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    load_entry_point('objection==1.4.1', 'console_scripts', 'objection')()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/objection/console/cli.py", line 244, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/dist-packages/objection/commands/mobile_packages.py", line 182, in patch_android_apk
    shutil.copyfile(patcher.get_patched_apk_path(), os.path.join(os.path.abspath('.'), destination))
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpj_y1o4j0.apktemp.aligned.objection.apk'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpj_y1o4j0.apktemp.objection.apk'

```

**Comment by leonjza** [comment]
Unfortunately this APK is going to need manual patching based on the fact that `apktool` could not unpack the original source APK. I suggest you start by running `apktool d source.apk` and follow the process from there to see what is needed to get the unpacking to work.

One thing you can try is to tack on the `--skip-resources` flag to see if that helps. This simply adds the same flag to apktool which sometimes is enough to continue with the patching process.

Good luck!
