### ISSUE TITLE
Smali not found (Unable to extract smali)

### ISSUE THREAD

**Issue by pakesusu** [sensepost/objection#128]
Hi,

when trying to patch google.apk, objection was fail

```
> objection patchapk -s /Users/macbook/Downloads/google.apk --skip-resources
> No architecture specified. Determining it using `adb`...
> Detected target device architecture as: arm64-v8a
> Using latest Github gadget version: 12.1.0
> Patcher will be using Gadget version: 12.1.0
> Unpacking /Users/macbook/Downloads/google.apk
> App already has android.permission.INTERNET
> Smali not found in smali directory. This might be a multidex APK. Searching...
> Traceback (most recent call last):
>   File "/usr/local/bin/objection", line 11, in <module>
>     load_entry_point('objection==1.4.1', 'console_scripts', 'objection')()
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/objection-1.4.1-py3.7.egg/objection/console/cli.py", line 244, in patchapk
>     patch_android_apk(**locals())
>   File "/usr/local/lib/python3.7/site-packages/objection-1.4.1-py3.7.egg/objection/commands/mobile_packages.py", line 161, in patch_android_apk
>     patcher.inject_load_library()
>   File "/usr/local/lib/python3.7/site-packages/objection-1.4.1-py3.7.egg/objection/utils/patchers/android.py", line 555, in inject_load_library
>     raise Exception('Unable to find smali to patch!')
> Exception: Unable to find smali to patch!
> Cleaning up temp files...
> Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/rc/2gxw3bf900v2xvfb9wyqt1ym0000gp/T/tmp5fy5_27o.apktemp.objection.apk'
```

Using another apk was fine, using -D / --skip-resouces was not help, i've use all parameters but still no luck.

Using apktool was fine, i can see smali files on extracted folder.

```
> Ms-MacBook-Pro:Downloads macbook$ apktool decode google.apk 
> I: Using Apktool 2.3.3 on google.apk
> I: Loading resource table...
> I: Decoding AndroidManifest.xml with resources...
> I: Loading resource table from file: /Users/macbook/Library/apktool/framework/1.apk
> I: Regular manifest package...
> I: Decoding file-resources...
> I: Decoding values */* XMLs...
> I: Baksmaling classes.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
> Ms-MacBook-Pro:Downloads macbook$ ls -l google/smali/okhttp3/ -F
> ls: -F: No such file or directory
> google/smali/okhttp3/:
> total 1696
> -rw-r--r--   1 macbook  staff  16143 Aug 28 16:51 Address.smali
> -rw-r--r--   1 macbook  staff    687 Aug 28 16:51 Authenticator$1.smali
> -rw-r--r--   1 macbook  staff    593 Aug 28 16:51 Authenticator.smali
> -rw-r--r--   1 macbook  staff   2288 Aug 28 16:51 Cache$1.smali
> -rw-r--r--   1 macbook  staff   4616 Aug 28 16:51 Cache$2.smali
> -rw-r--r--   1 macbook  staff   2723 Aug 28 16:51 Cache$CacheRequestImpl$1.smali
> -rw-r--r--   1 macbook  staff   3196 Aug 28 16:51 Cache$CacheRequestImpl.smali
> -rw-r--r--   1 macbook  staff   1360 Aug 28 16:51 Cache$CacheResponseBody$1.smali
> -rw-r--r--   1 macbook  staff   2917 Aug 28 16:51 Cache$CacheResponseBody.smali
> -rw-r--r--   1 macbook  staff  27480 Aug 28 16:51 Cache$Entry.smali
```

Is any step I missing out? thanks.

**Comment by pakesusu** [comment]
no luck either in Kali linux / Single user root distro, tmp folder was fine, i can write all in /

**Comment by leonjza** [comment]
This error is because objection could not automatically determine where to inject the load library call for the Frida gadget in the target application. Unfortunately in this case you will have to manually patch it at a suitable location. If you are interested in how objection does the patching, have a look at [these lines](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L487-L548).

In the future I may add a flag that will let you specify a target method to patch.

**Comment by pakesusu** [comment]
thanks leonjza, and yes after searching through smali code, i dont see string beside Object.

will look at this, and appreciate for your answer 🥇
