### ISSUE TITLE
Stop ipa patching if provisioning profile is not found

### ISSUE THREAD

**Issue by TheDauntless** [sensepost/objection#145]
A sample run of patching an ipa:

```
 objection patchipa -s xxx.ipa -c xxxxxxx                                                                                                                                                   [14:51:52]
Using latest Github gadget version: 12.2.9
Patcher will be using Gadget version: 12.2.9
No provision file specified, searching for one...
No provisioning files found. Please specify one or generate one by building an app.
Working with app: xxx-UAT.app
Bundle identifier is: xxxxxxx
Codesigning 14 .dylib's with signature xxxxxxxxx
Code signing: libswiftCoreImage.dylib
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
.... Some stuff....

Creating new archive with patched contents...
Codesigning patched IPA...
Traceback (most recent call last):
  File "/Users/xxxx/Security/iOS/env/bin/objection", line 11, in <module>
... some stuff...
  File "/Users/xxxxx/Security/iOS/env/lib/python3.6/site-packages/objection/utils/patchers/ios.py", line 405, in archive_and_codesign
    self.patched_ipa_path
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
```

Eventually objection crashes because a valid profile could not be found. Shouldn't objection just stop when it didn't identify a correct profile?

**Comment by leonjza** [comment]
It should! I plan on giving the patchers some more attention (and fix this too) in the `typescript_agent` branch before merging that to master too!
