### ISSUE TITLE
Failed to patch universal/multidex .apk

### ISSUE THREAD

**Issue by evandrix** [sensepost/objection#162]
```
$ objection patchapk -s com.facebook.mlite-v45.0.0.14.193-131209665.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: x86
Using latest Github gadget version: 12.2.26
Patcher will be using Gadget version: 12.2.26
Unpacking com.facebook.mlite-v45.0.0.14.193-131209665.apk
App already has android.permission.INTERNET
Smali not found in smali directory. This might be a multidex APK. Searching...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/objection-1.4.3-py3.7.egg/objection/console/cli.py", line 244, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.7/site-packages/objection-1.4.3-py3.7.egg/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library()
  File "/usr/local/lib/python3.7/site-packages/objection-1.4.3-py3.7.egg/objection/utils/patchers/android.py", line 552, in inject_load_library
    raise Exception('Unable to find smali to patch!')
Exception: Unable to find smali to patch!
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmp2m81mpsl.apktemp.objection.apk'
```

**Comment by leonjza** [comment]
Using the the `--pause` flag may be useful for this before the patching continues with the repackaging, fwiw.
