### ISSUE TITLE
Unable to find process with name and another problems

### ISSUE THREAD

**Issue by shplishka** [sensepost/objection#166]

**Comment by shplishka** [comment]
I try to do this tut: https://www.frida.re/docs/functions/
and i got this exception:

> C:\Users\Michael\Desktop>python hook.py 00401460
Traceback (most recent call last):
  File "hook.py", line 5, in <module>
    session = frida.attach("hello")
  File "C:\Program Files\Python37\lib\site-packages\frida\__init__.py", line 59, in attach
    return get_local_device().attach(target)
  File "C:\Program Files\Python37\lib\site-packages\frida\core.py", line 110, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "C:\Program Files\Python37\lib\site-packages\frida\core.py", line 128, in _pid_of
    return self.get_process(target).pid
  File "C:\Program Files\Python37\lib\site-packages\frida\core.py", line 75, in get_process
    raise _frida.ProcessNotFoundError("unable to find process with name '%s'" % process_name)
frida.ProcessNotFoundError: unable to find process with name 'hello'

**Comment by leonjza** [comment]
Looks like you are trying to use Frida core. For issues with Frida, I suggest you rather refer to the applicable projects Github [here](https://github.com/frida/frida).

For what it's worth, `frida.attach()` wants a process name and this fails as no process called `hello` existed when you ran your script.
