### ISSUE TITLE
No such file 'frida-codesigned' because of 'Unexpected token function'

### ISSUE THREAD

**Issue by veeralpatel** [sensepost/objection#183]
I'm getting the following error while trying patch an IPA:

```
Using latest Github gadget version: 12.3.1
Patcher will be using Gadget version: 12.3.1
No provision file specified, searching for one...
Found provision file /Users/veeralpatel/Library/Developer/Xcode/DerivedData/Audio-Levels-amwjhvpnfxoijzfsiaujytlbxwcv/Build/Products/Debug-iphoneos/Audio-Levels.app/embedded.mobileprovision expiring in 326 days, 4:57:28.997518
Found provision file /Users/veeralpatel/Library/Developer/Xcode/DerivedData/compound-test-bdqkczxhrevzfwbovdwxlkfllmgc/Build/Products/Debug-iphoneos/compound-test.app/embedded.mobileprovision expiring in 7 days, 5:51:01.997518
Found a valid provisioning profile
Working with app: Shareworks.app
Bundle identifier is: com.solium.SwPtpMobile
Codesigning 15 .dylib's with signature [REDACTED]
Code signing: libswiftCoreImage.dylib
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
Code signing: libswiftCoreGraphics.dylib
Code signing: libswiftUIKit.dylib
Code signing: libswiftMetal.dylib
Code signing: libswiftDispatch.dylib
Code signing: libswiftos.dylib
Code signing: libswiftCoreFoundation.dylib
Code signing: FridaGadget.dylib
Code signing: libswiftDarwin.dylib
Code signing: libswiftQuartzCore.dylib
Code signing: libswiftAccelerate.dylib
Code signing: libswiftFoundation.dylib
Code signing: libswiftCoreLocation.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
/usr/local/lib/node_modules/applesign/bin/applesign.js:16
async function main (argv) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

Copying final ipa from /var/folders/jd/4vz0kcc547v46dtqpytt03jc0000gn/T/Shareworks 5.5.1-frida-codesigned.ipa to current directory...
Traceback (most recent call last):
  File "/Users/veeralpatel/virtual-python3.6/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/objection/console/cli.py", line 210, in patchipa
    patch_ios_ipa(**locals())
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 75, in patch_ios_ipa
    os.path.join(os.path.abspath('.'), os.path.basename(patcher.get_patched_ipa_path())))
  File "/Users/veeralpatel/virtual-python3.6/lib/python3.6/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/jd/4vz0kcc547v46dtqpytt03jc0000gn/T/Shareworks 5.5.1-frida-codesigned.ipa'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/jd/4vz0kcc547v46dtqpytt03jc0000gn/T/Shareworks 5.5.1-frida-codesigned.ipa'
```

**Comment by akohlsmith** [comment]
I am getting this as well. You closed your own issue; what did you do to resolve it?
