### ISSUE TITLE
Encrypted IPA

### ISSUE THREAD

**Issue by veeralpatel** [sensepost/objection#184]
I'm trying to patch an IPA according to the following [guide](https://github.com/sensepost/objection/wiki/Patching-iOS-Applications) and I'm getting the following error saying that the IPA is encrypted:

```
Using latest Github gadget version: 12.3.1
Patcher will be using Gadget version: 12.3.1
No provision file specified, searching for one...
Found provision file /Users/veeralpatel/Library/Developer/Xcode/DerivedData/Audio-Levels-amwjhvpnfxoijzfsiaujytlbxwcv/Build/Products/Debug-iphoneos/Audio-Levels.app/embedded.mobileprovision expiring in 326 days, 4:39:29.175272
Found provision file /Users/veeralpatel/Library/Developer/Xcode/DerivedData/compound-test-bdqkczxhrevzfwbovdwxlkfllmgc/Build/Products/Debug-iphoneos/compound-test.app/embedded.mobileprovision expiring in 7 days, 5:33:02.175272
Found a valid provisioning profile
Working with app: Shareworks.app
Bundle identifier is: com.solium.SwPtpMobile
Codesigning 15 .dylib's with signature [redacted]
Code signing: libswiftCoreImage.dylib
Code signing: libswiftObjectiveC.dylib
Code signing: libswiftCore.dylib
Code signing: libswiftCoreGraphics.dylib
Code signing: libswiftUIKit.dylib
Code signing: libswiftMetal.dylib
Code signing: libswiftDispatch.dylib
Code signing: libswiftos.dylib
Code signing: libswiftCoreFoundation.dylib
Code signing: FridaGadget.dylib
Code signing: libswiftDarwin.dylib
Code signing: libswiftQuartzCore.dylib
Code signing: libswiftAccelerate.dylib
Code signing: libswiftFoundation.dylib
Code signing: libswiftCoreLocation.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Error: This IPA is encrypted
    at Applesign.signAppDirectory (/usr/local/lib/node_modules/applesign/index.js:87:15)
    at Applesign.signIPA (/usr/local/lib/node_modules/applesign/index.js:58:16)

``` 

I'm trying to patch a 3rd party app--is there anyway around this?

**Comment by leonjza** [comment]
The only way would be to use something like bfinject/clutch2/frida-ios-dump on a jailbroken device to dump a decrypted version of the target IPA for you. With that in mind, if you have a jailbroken device you can simply run frida-server and use it that way. If you have access to the developers of the target application, have them supply you with a build as they would submit to the App store.
