### ISSUE TITLE
iOS plist not respecting relative paths properly

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#197]
Attempting to use `ios plist cat Info.plist` gives an error, along the lines of the following: 

```
A Frida agent exception has occurred.
TypeError: cannot read property 'toString' of null
    at [anon] (duk_hobject_props.c:2384)
    at /script1.js:6293
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "c:\python37\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "c:\python37\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "c:\python37\lib\site-packages\objection\commands\ios\plist.py", line 29, in cat
    plist_data = api.ios_plist_read(plist)
  File "c:\python37\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "c:\python37\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: cannot read property 'toString' of null
    at [anon] (duk_hobject_props.c:2384)
    at /script1.js:6293
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)
```

This appears to be related to the command not respecting relative paths properly - using an absolute path works fine. Could this be related to #165?

**Comment by aph3rson** [comment]
Definitely is, same issue with using `os.path.join`. See `plist.py:26`:
 https://github.com/sensepost/objection/blob/805bf86db02c085f4f3c0be5eb5ef7f4df9a8f03/objection/commands/ios/plist.py#L24-L26

**Comment by aph3rson** [comment]
Patching `plist.py:26` to `plist = "/".join([pwd, plist])` works fine, I'll file a PR momentarily.
