### ISSUE TITLE
Can't patch apk :c

### ISSUE THREAD

**Issue by shadowzoom** [sensepost/objection#205]
I'm trying to patch apk and get this error:

```
objection patchapk --source com.****.apk --skip-resources
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 12.4.0
Patcher will be using Gadget version: 12.4.0
Unpacking com.***.apk
App already has android.permission.INTERNET
Unable to determine the launchable activity using aapt, trying to manually parse the AndroidManifest for activity aliases...
Traceback (most recent call last):
  File "/home/zoom/virtual-python3/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 322, in patchapk
    patch_android_apk(**locals())
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library()
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 529, in inject_load_library
    activity = self._get_launchable_activity().replace('.', '/')
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 294, in _get_launchable_activity
    manifest = self._get_android_manifest()
  File "/home/zoom/virtual-python3/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 239, in _get_android_manifest
    return ElementTree.parse(os.path.join(self.apk_temp_directory, 'AndroidManifest.xml'))
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 597, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmptc_94sfi.apktemp.objection.apk'
```

As i read this needs to be manually patched... But my knowledgence is beyond of my undesrstating... :c
Can please somebody help me to patch apk? I need just one thing, to intercept traffic from this apk, sadly frida is not properly working..

**Comment by leonjza** [comment]
Unfortunately, you will need to manually reverse engineer this application to continue. In a future version I may add support to specify an arbitrary class to patch, but that is not in the immediate roadmap for me now.

Good luck!
