### ISSUE TITLE
Fail rebuilding APK

### ISSUE THREAD

**Issue by raigorx** [sensepost/objection#212]
Playing around with twitter splited apk on windows

```
    C:\test\Android\com.twitter.android>dir
     El volumen de la unidad C no tiene etiqueta.
     El número de serie del volumen es: F4CC-C763
    
     Directorio de C:\test\Android\com.twitter.android
    
    18/03/2019  10:30 a.m.    <DIR>          .
    18/03/2019  10:30 a.m.    <DIR>          ..
    18/03/2019  10:30 a.m.        17.942.356 base.apk
    18/03/2019  10:15 a.m.           342.881 split_config.en.apk
    18/03/2019  10:15 a.m.         1.753.184 split_config.x86.apk
    18/03/2019  10:16 a.m.         2.162.062 split_config.xxxhdpi.apk
```

```
    C:\test\Android\com.twitter.android>objection patchapk -s base.apk
    No architecture specified. Determining it using `adb`...
    Detected target device architecture as: x86
    Using latest Github gadget version: 12.4.1
    Patcher will be using Gadget version: 12.4.1
    Unpacking base.apk
    App already has android.permission.INTERNET
    Smali not found in smali directory. This might be a multidex APK. Searching...
    Found smali at: C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp\smali_classes2\com/twitter/android/StartActivity.smali
    Reading smali from: C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp\smali_classes2\com/twitter/android/StartActivity.smali
    Injecting loadLibrary call at line: 6
    Writing patched smali back to: C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp\smali_classes2\com/twitter/android/StartActivity
    .smali
    Creating library path: C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp\lib\x86
    Copying Frida gadget to libs path...
    Rebuilding the APK with the frida-gadget loaded...
    Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error:

    Exception in thread "main" org.jf.util.ExceptionWithContext: Exception occurred while writing code_item for method Lcom/twitter/metrics
    /ForegroundMetricTracker$BackgroundBehavior;->values()[Lcom/twitter/metrics/ForegroundMetricTracker$BackgroundBehavior;
            at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:917)
            at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:341)
            at org.jf.dexlib2.writer.DexWriter.writeTo(DexWriter.java:297)
            at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:61)
            at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
            at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:419)
            at brut.androlib.Androlib.buildNonDefaultSources(Androlib.java:365)
            at brut.androlib.Androlib.build(Androlib.java:303)
            at brut.androlib.Androlib.build(Androlib.java:269)
            at brut.apktool.Main.cmdBuild(Main.java:247)
            at brut.apktool.Main.main(Main.java:79)
    Caused by: org.jf.util.ExceptionWithContext: Error while writing instruction at code offset 0x2
            at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1190)
            at org.jf.dexlib2.writer.DexWriter.writeDebugAndCodeItems(DexWriter.java:913)
            ... 10 more
    Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536
            at org.jf.dexlib2.writer.DexDataWriter.writeUshort(DexDataWriter.java:116)
            at org.jf.dexlib2.writer.InstructionWriter.write(InstructionWriter.java:356)
            at org.jf.dexlib2.writer.DexWriter.writeCodeItem(DexWriter.java:1150)
            ... 11 more


    Built new APK with injected loadLibrary and frida-gadget
    Signing new APK.
    Signing the new APK may have failed.
    jarsigner: unable to open jar file: C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp.objection.apk


    Signed the new APK
    Performing zipalign
    Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error:

    Unable to open 'C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp.objection.apk' as zip archive

    Zipalign completed
    Copying final apk from C:\Users\raigorx\AppData\Local\Temp\tmpxcffppp2.apktemp.aligned.objection.apk to base.objection.apk in current d
    irectory...
    Traceback (most recent call last):
    File "C:\Users\raigorx\AppData\Local\Programs\Python\Python37\Scripts\objection-script.py", line 11, in <module>
        load_entry_point('objection==1.5.2', 'console_scripts', 'objection')()
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
        return self.main(*args, **kwargs)
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
        rv = self.invoke(ctx)
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
        return callback(*args, **kwargs)
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\objection\console\cli.py", line 322, in patchapk
        patch_android_apk(**locals())
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\site-packages\objection\commands\mobile_packages.py", line 182, in
    patch_android_apk
        shutil.copyfile(patcher.get_patched_apk_path(), os.path.join(os.path.abspath('.'), destination))
    File "c:\users\raigorx\appdata\local\programs\python\python37\lib\shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\raigorx\\AppData\\Local\\Temp\\tmpxcffppp2.apktemp.aligned.objectio
    n.apk'
    Cleaning up temp files...
    Failed to cleanup with error: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\\Users\\raigorx\\AppData\\Local\\
    Temp\\tmpxcffppp2.apktemp.objection.apk'
```

Googling I found:
[https://developer.android.com/studio/build/multidex](https://developer.android.com/studio/build/multidex)

It says 

> The Dalvik Executable specification limits the total number of methods that can be referenced within a single DEX file to 65,536—including Android framework methods, library methods, and methods in your own code. In the context of computer science, the term Kilo, K, denotes 1024 (or 2^10). Because 65,536 is equal to 64 X 1024, this limit is referred to as the '64K reference limit'.

This match with:

> Caused by: org.jf.util.ExceptionWithContext: Unsigned short value out of range: 65536

```
C:\test\Android\com.twitter.android>apktool --version
2.4.0
```

Note: I can decode and build base.apk directly from apktool

[base.apk.zip](https://github.com/sensepost/objection/files/2979124/base.apk.zip)
[split_config.en.apk.zip](https://github.com/sensepost/objection/files/2979142/split_config.en.apk.zip)
[split_config.x86.apk.zip](https://github.com/sensepost/objection/files/2979144/split_config.x86.apk.zip)
[split_config.xxxhdpi.apk.zip](https://github.com/sensepost/objection/files/2979145/split_config.xxxhdpi.apk.zip)

**Comment by leonjza** [comment]
Did you use apktool without any flags? Could you try the `--skip-resources` flag in objection?

**Comment by raigorx** [comment]
Yes, I used apktool without any flag

Yes, I tried --skip-resources same error

No idea if it is related to the problem but trying to convert every classes*.dex using dex2jar give me an error in the last one

```
C:\test\Android\com.twitter.android\baseZipped>d2j-dex2jar classes.dex
dex2jar classes.dex -> .\classes-dex2jar.jar

C:\test\Android\com.twitter.android\baseZipped>d2j-dex2jar classes2.dex
dex2jar classes2.dex -> .\classes2-dex2jar.jar

C:\test\Android\com.twitter.android\baseZipped>d2j-dex2jar classes3.dex
dex2jar classes3.dex -> .\classes3-dex2jar.jar

C:\test\Android\com.twitter.android\baseZipped>d2j-dex2jar classes4.dex
dex2jar classes4.dex -> .\classes4-dex2jar.jar

C:\test\Android\com.twitter.android\baseZipped>d2j-dex2jar classes5.dex
dex2jar classes5.dex -> .\classes5-dex2jar.jar
Detail Error Information in File .\classes5-error.zip
Please report this file to one of following link if possible (any one).
    https://sourceforge.net/p/dex2jar/tickets/
    https://bitbucket.org/pxb1988/dex2jar/issues
    https://github.com/pxb1988/dex2jar/issues [no attachment support, not preferred]
    dex2jar@googlegroups.com
```

**Comment by hduarte** [comment]
@raigorx try to update apktool to its latest version and try with java/openjdk 8 and/or 11

**Comment by raigorx** [comment]
> @raigorx try to update apktool to its latest version and try with java/openjdk 8 or 11

It was time ago but I remember the problem is with apktool that isnt good handling multidex splited apks

**Comment by leonjza** [comment]
This is definitely isolated to apktool. I am able to replicate this by decoding the the target APK, modifying the smali of `StartActivity.smali` and then rebuilding the APK, causing in the same error.

I think it would be best to do a bug report for `apktool` from here.

**Comment by sagiashok** [comment]
i am getting same issue please help me
