### ISSUE TITLE
Memory search not working since v1.5.3 update

### ISSUE THREAD

**Issue by fuzzKitty** [sensepost/objection#213]
Hi,
First of all, Kudos for the great work you do. 
Secondly, I wanted to report an issue I have been experiencing since the last update to v1.5.3; memory search doesn't work and throws the following exception:

``` 
com.x.x.x on (samsung: 7.0) [usb] # memory search "blabla"                                       
Searching for: blabla
A Frida agent exception has occurred.
Error: invalid match pattern
    at /script1.js:5507
    at map (native)
    at /script1.js:5510
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/dist-packages/objection/commands/memory.py", line 187, in find_pattern
    data = api.memory_search(pattern)
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: invalid match pattern
    at /script1.js:5507
    at map (native)
    at /script1.js:5510
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)
```

**Comment by leonjza** [comment]
Hey, the `invalid match pattern` error implies that you did not provide bytes to search for (`blabla` is not valid hex). If you are looking for a string, add the `--string` flag. All objection commands contain help pages which are accessible by simply adding `help` in front of your command.

I have added additional enumeration of writable pages as well in https://github.com/sensepost/objection/commit/74bd94dca68500d7da6638d848f13a186685f470 which should land in a minor version release later today.

**Comment by fuzzKitty** [comment]
Hi @leonjza , sorry, I had tried to replicate the error and forgot --string so I ended up posting the wrong output.
Please take a look at this, which is the actual error I get (I've also added a screenshot this time):

![image](https://user-images.githubusercontent.com/31076796/55071199-9792be00-5090-11e9-8bd5-f406f1865282.png)

```
com.x.x.xon (iPhone: 12.1.1) [usb] # memory search "March2019" --string                         
Searching for: 4d 61 72 63 68 32 30 31 39
A Frida agent exception has occurred.
Error: access violation accessing 0x106524000
    at /script1.js:5526
    at map (native)
    at /script1.js:5533
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/dist-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/dist-packages/objection/commands/memory.py", line 199, in find_pattern
    data = api.memory_search(pattern, _should_only_dump_offsets(args))
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.7/dist-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: access violation accessing 0x106524000
    at /script1.js:5526
    at map (native)
    at /script1.js:5533
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:25)
```

**Comment by leonjza** [comment]
Do you have the latest version installed? I added enumeration of writable pages too, but ultimately this may be failing as the page itself may have had its protection changed (or has been reallocated) by the time the search came past.

**Comment by shunlibest** [comment]
I also meet this problem, you can try to use the [tab] button to complete; maybe your character is wrong.
