### ISSUE TITLE
Issues with Keychain dump & other functions.

### ISSUE THREAD

**Issue by chackokavanattu12** [sensepost/objection#215]
```
**net.ifao.abcd on (iPhone: 11.2.5) [usb] # ios sslpinning disable --quiet                                                                
(agent) Quiet mode enabled. Not reporting invocations.
(agent) Hooking common framework methods
A Frida agent exception has occurred.
Error: missing argument
    at script1.js:6241
    at script1.js:6256
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)

Python stack trace: Traceback (most recent call last):
  File "/root/objection/lib/python3.6/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/root/objection/lib/python3.6/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/root/objection/lib/python3.6/site-packages/objection/commands/ios/pinning.py", line 26, in ios_disable
    api.ios_pinning_disable(_should_be_quiet(args))
  File "/root/objection/lib/python3.6/site-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/root/objection/lib/python3.6/site-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: missing argument
    at script1.js:6241
    at script1.js:6256
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)

net.ifao.abcd on (iPhone: 11.2.5) [usb] # ios keychain dump                                                                             
Note: You may be asked to authenticate using the devices passcode or TouchID
Save the output by adding `--json keychain.json` to this command
Dumping the iOS keychain...
A Frida agent exception has occurred.
TypeError: undefined not callable (property 'readPointer' of [object Object])
    at [anon] (duk_js_call.c:2847)
    at script1.js:5904
    at map (native)
    at script1.js:5935
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)

Python stack trace: Traceback (most recent call last):
  File "/root/objection/lib/python3.6/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/root/objection/lib/python3.6/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/root/objection/lib/python3.6/site-packages/objection/commands/ios/keychain.py", line 65, in dump
    keychain = api.ios_keychain_list()
  File "/root/objection/lib/python3.6/site-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/root/objection/lib/python3.6/site-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: undefined not callable (property 'readPointer' of [object Object])
    at [anon] (duk_js_call.c:2847)
    at script1.js:5904
    at map (native)
    at script1.js:5935
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)**
```

**Comment by leonjza** [comment]
Hey,

Please could you run objection with the `--debug` flag before the `explore` subcommand and paste the error you get?

**Comment by chackokavanattu12** [comment]
root@startr3k:~# objection -g 6877 -d explore
[debug] Agent path is: /usr/local/lib/python3.6/dist-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `iOS Device`
[debug] Attempting to attach to process: `6877`
[debug] Process attached!
Agent injected and responds ok!

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.5.4

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
net.ifao.abcd on (iPhone: 11.2.5) [usb] # ios keychain dump                                                                             
Note: You may be asked to authenticate using the devices passcode or TouchID
Save the output by adding `--json keychain.json` to this command
Dumping the iOS keychain...
A Frida agent exception has occurred.
TypeError: undefined not callable (property 'readPointer' of [object Object])
    at [anon] (duk_js_call.c:2847)
    at src/ios/keychain.ts:99
    at map (native)
    at src/ios/keychain.ts:140
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.6/dist-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.6/dist-packages/objection/commands/ios/keychain.py", line 65, in dump
    keychain = api.ios_keychain_list()
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "/usr/local/lib/python3.6/dist-packages/frida/core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: undefined not callable (property 'readPointer' of [object Object])
    at [anon] (duk_js_call.c:2847)
    at src/ios/keychain.ts:99
    at map (native)
    at src/ios/keychain.ts:140
    at e (frida/runtime/message-dispatcher.js:45)
    at t (frida/runtime/message-dispatcher.js:24)

**Comment by leonjza** [comment]
Ah, what version of the Frida server are you using? You may need to upgrade this as some of the JavaScript API's have changed.

**Comment by chackokavanattu12** [comment]
Version is 12.4.5

**Comment by chackokavanattu12** [comment]
i upgraded, Its working fine now, Thanks for letting me know.

**Comment by leonjza** [comment]
Alright, I am about 99% certain this is not a bug but rather just a local quirk where something Frida-related is not up to date. I am reasoning as follows:

> at src/ios/keychain.ts:99

From the debug output we can see the affected LoC is [this](https://github.com/sensepost/objection/blob/b28facb7306ab8fcaf3fe8ebd2cda2e1e2a2295e/agent/src/ios/keychain.ts#L99).

```javascript
const searchResults: NSDictionary = new ObjC.Object(resultsPointer.readPointer());
```

[This](https://github.com/sensepost/objection/commit/613be5a8c66e2c498a4d951046d877465fc8a783#diff-0186a529f0fd0460a670c51479a83adbR100) commit changed the pointer read from the `Memory` object to match the [API changes](https://github.com/frida/frida-gum/blob/master/bindings/gumjs/types/frida-gum/frida-gum.d.ts#L1241), adding the `readPointer()` method to a `NativePointer`. The error in your stack trace says that this is not a callable on the `NativePointer`, which lead me to think that the frida-server was not up to date.

> TypeError: undefined not callable (property 'readPointer' of [object Object])

Could you possibly get together a smaller script that creates a new `NativePointer` and reads it to see if that is reproducible? Other things to try could be to ensure that everything Frida related us up to date.

**Comment by leonjza** [comment]
> i upgraded, Its working fine now, Thanks for letting me know.

Ah, I saw this too late. Awesome 🚀
