### ISSUE TITLE
Cannot disconnect from SQLite database

### ISSUE THREAD

**Issue by aph3rson** [sensepost/objection#228]
**Describe the bug**
After connecting to a SQLite database, it's not possible to disconnect - an error is returned claiming that the file is already open.

This appears to be an error in `_get_connection()`:
https://github.com/sensepost/objection/blob/feff2a2fa1e9269b6ca077e0e708dc682affaee1/objection/commands/sqlite.py#L12-L20

Notice that `return sqlite3.connect(...)` is called, however `close()` is never called on the result.

There are multiple possible solutions here, though I'd recommend something along the lines of the following:
https://github.com/sensepost/objection/blob/feff2a2fa1e9269b6ca077e0e708dc682affaee1/objection/commands/sqlite.py#L146-L155

Using something along the lines of `with _get_connection() as connection:` would be very Pythonic, but I'm not sure about the `__exit__` behavior on the Connection object. In any sense, `close()` needs to be called on the resultant Connection - otherwise, there's an open file descriptor still, and the file can't be deleted.

**To Reproduce**
1. Connect to any running application with an SQLite DB contained within.
2. Run `sqlite connect sqlite.db`, followed by `sqlite disconnect`

**Expected behavior**
The database immediately disconnects

**Evidence / Logs / Screenshots**
```text
com.company.app on (iPad: 11.4) [net] # sqlite connect sqlite.db
Caching local copy of database file...
Downloading /var/mobile/Containers/Data/Application/67008B70-A410-43F8-A994-02997C2FADFE/Documents/sqlite.db to C:\Users\IWILLI~1\AppData\Local\Temp\tmp2rbclwj6objection.sqlite
Streaming file from device...
Writing bytes to destination...
Successfully downloaded /var/mobile/Containers/Data/Application/67008B70-A410-43F8-A994-02997C2FADFE/Documents/sqlite.db to C:\Users\IWILLI~1\AppData\Local\Temp\tmp2rbclwj6objection.sqlite
Validating SQLite database format
Connected to SQLite database at: sqlite.db
com.company.app on (iPad: 11.4) [net] # sqlite disconnect
Make sure you run 'sqlite sync' if needed!
Are you sure you want to disconnect? [y/N]: y
Disconnecting database: sqlite.db
[sqlite manager] Removing cached copy of SQLite database: sqlite.db at C:\Users\IWILLI~1\AppData\Local\Temp\tmp2rbclwj6objection.sqlite
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IWILLI~1\\AppData\\Local\\Temp\\tmp2rbclwj6objection.sqlite'

Python stack trace: Traceback (most recent call last):
  File "c:\python37\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "c:\python37\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "c:\python37\lib\site-packages\objection\commands\sqlite.py", line 106, in disconnect
    sqlite_manager_state.cleanup()
  File "c:\python37\lib\site-packages\objection\state\sqlite.py", line 35, in cleanup
    os.remove(self.temp_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IWILLI~1\\AppData\\Local\\Temp\\tmp2rbclwj6objection.sqlite'
```

**Environment (please complete the following information):**
 - Device: 2018 iPad 
 - OS: iOS 11.4.1/Windows 10
 - Frida Version 12.4.8
- Objection Version 1.5.2

**Additional context**
This appears to be cross-platform.

**Comment by leonjza** [comment]
Could this be Windows specific?

```
com.reddit.frontpage on (samsung: 7.1.2) [usb] # sqlite connect reddit_analytics.db
Caching local copy of database file...
Downloading /data/user/0/com.reddit.frontpage/databases/reddit_analytics.db to /var/folders/nn/7rzmzs_920n8qvff8n9nf1rm0000gn/T/tmpyveshkooobjection.sqlite
Streaming file from device...
Writing bytes to destination...
Successfully downloaded /data/user/0/com.reddit.frontpage/databases/reddit_analytics.db to /var/folders/nn/7rzmzs_920n8qvff8n9nf1rm0000gn/T/tmpyveshkooobjection.sqlite
Validating SQLite database format
Connected to SQLite database at: reddit_analytics.db
com.reddit.frontpage on (samsung: 7.1.2) [usb] # sqlite disconnect
Make sure you run 'sqlite sync' if needed!
Are you sure you want to disconnect? [y/N]: y
Disconnecting database: reddit_analytics.db
[sqlite manager] Removing cached copy of SQLite database: reddit_analytics.db at /var/folders/nn/7rzmzs_920n8qvff8n9nf1rm0000gn/T/tmpyveshkooobjection.sqlite
com.reddit.frontpage on (samsung: 7.1.2) [usb] #
```

**Comment by leonjza** [comment]
I actually replaced my own implementation here with lite-cli a while back. I suspect this may no longer be an issue now.
