### ISSUE TITLE
PatchAPK fails on apk files with parentheses in the name

### ISSUE THREAD

**Issue by RoganDawes** [sensepost/objection#234]
**Describe the bug**
Running ```objection patchapk 'com.example.app(1).apk'``` fails with an exception.

**To Reproduce**
1. Create an APK.
2. Rename/copy to a filename with a ```(1)``` in the name.
3. Run ```objection patchapk 'com.example.app(1).apk'```

**Expected behavior**

**Evidence / Logs / Screenshots**
```text
$ objection --debug patchapk --source com.example.app\(28\).apk 
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 12.5.8
Patcher will be using Gadget version: 12.5.8
Unpacking com.example.app(28).apk
An error may have occurred while extracting the APK.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/home/rogan/bin/apktool decode -f "" -o /tmp/tmpepkiwdmb.apktemp com.example.app(28).apk'

An error may have occurred while running aapt.
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/home/rogan/bin/aapt dump badging com.example.app(28).apk'

Traceback (most recent call last):
  File "/home/rogan/.local/bin/objection", line 11, in <module>
    load_entry_point('objection==1.6.4', 'console_scripts', 'objection')()
  File "/home/rogan/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rogan/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/rogan/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rogan/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rogan/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rogan/.local/lib/python3.7/site-packages/objection/console/cli.py", line 342, in patchapk
    patch_android_apk(**locals())
  File "/home/rogan/.local/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 153, in patch_android_apk
    patcher.inject_internet_permission(skip_resources=skip_resources)
  File "/home/rogan/.local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 389, in inject_internet_permission
    xml = self._get_android_manifest()
  File "/home/rogan/.local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 239, in _get_android_manifest
    return ElementTree.parse(os.path.join(self.apk_temp_directory, 'AndroidManifest.xml'))
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.7/xml/etree/ElementTree.py", line 587, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpepkiwdmb.apktemp/AndroidManifest.xml'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpepkiwdmb.apktemp.objection.apk'
```

**Environment (please complete the following information):**
 - Device: Android
 - Objection Version: 1.6.4

**Comment by Cablethief** [comment]
This is also present when doing IPAs.

**Comment by aph3rson** [comment]
@RoganDawes @Cablethief Can you confirm what OS you're running this on? I suspect this is an issue with running this on a non-Windows host, as `list2cmdline` is used to construct the calls to `aapt`/`apktool`/etc., and is primarily used to apply `cmd.exe`-type escaping.

**Comment by RoganDawes** [comment]
This was Linux.

**Comment by aph3rson** [comment]
Kind of my suspicion here - I'm imagining we'll need a call other than the one I mentioned above to perform Unix-style escaping for delegator jobs. @leonjza thoughts?

**Comment by RoganDawes** [comment]
/me pictures creating an APK with backticks in the name :-D

**Comment by cpholguera** [comment]
What about using pathlib. It handles this kind of issues with files and paths in Windows/Linux and it's built-in in python 3

**Comment by leonjza** [comment]
The way commands are handled internally may need a revisit yeah. We have the need to run many external commands as already mentioned by @aph3rson, which is something delegator handles for us now. If there are better alternatives, or, if it makes sense to just write our own helper for it (like for better cross platform support), let's do it!
