### ISSUE TITLE
Trying  get work 

### ISSUE THREAD

**Issue by the1220** [sensepost/objection#235]
```
ber$ objection
Traceback (most recent call last):
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (prompt-toolkit 2.0.9 (/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages), Requirement.parse('prompt_toolkit<2.0.0,>=1.0.15'), {'objection'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/svengarber/.pyenv/versions/3.7.0/bin/objection", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/svengarber/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prompt_toolkit<2.0.0,>=1.0.15' distribution was not found and is required by objection
```

**Comment by leonjza** [comment]
It looks like you may have installed something in that pyenv that downgraded python-prompt-toolkit. objection currently requires [v2](https://github.com/sensepost/objection/blob/83adab816b9fb9f3d2cd723005ed2b3d00ccf5b2/requirements.txt#L3) of the lib.
