### ISSUE TITLE
iOS SSL Pinning Error: TypeError: cannot read property 'implementation' of undefined

### ISSUE THREAD

**Issue by ldbfpiaoran** [sensepost/objection#243]
hello   the  error su as  
It use --debug

```
com.meituan.imeituan on (iPhone: 9.3.1) [usb] # ios sslpinning disable
- [incoming message] ------------------
{
  "payload": "\u001b[90mHooking common framework methods\u001b[39m",
  "type": "send"
}
- [./incoming message] ----------------
(agent) Hooking common framework methods
- [incoming message] ------------------
{
  "payload": "\u001b[90m[94vrm73nzre] \u001b[39mFound AFNetworking library. Hooking known pinning methods.",
  "type": "send"
}
- [./incoming message] ----------------
(agent) [94vrm73nzre] Found AFNetworking library. Hooking known pinning methods.
A Frida agent exception has occurred.
TypeError: cannot read property 'implementation' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56648)
    at src/ios/pinning.ts:41
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "c:\users\cuijianxiong\appdata\local\programs\python\python37\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "c:\users\cuijianxiong\appdata\local\programs\python\python37\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "c:\users\cuijianxiong\appdata\local\programs\python\python37\lib\site-packages\objection\commands\ios\pinning.py", line 26, in ios_disable
    api.ios_pinning_disable(_should_be_quiet(args))
  File "c:\users\cuijianxiong\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "c:\users\cuijianxiong\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: cannot read property 'implementation' of undefined
    at [anon] (../../../frida-gum/bindings/gumjs/duktape.c:56648)
    at src/ios/pinning.ts:41
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)
```

**Comment by leonjza** [comment]
Looks like this is failing on [`AFSecurityPolicy["- setSSLPinningMode:"].implementation`](https://github.com/sensepost/objection/blob/2e92215f21c4b6b98e6bb7bdc9f7fadf813aaaf4/agent/src/ios/pinning.ts#L61). Could you investigate your app to see if `-[AFSecurityPolicy setSSLPinningMode:]` really isn't there?

**Comment by ldbfpiaoran** [comment]
@leonjza    Hello, what do I need to do?

**Comment by leonjza** [comment]
Reverse engineer your target application and inspect `AFSecurityPolicy`.

**Comment by ldbfpiaoran** [comment]
@leonjza  He doesn't seem to have AFSecurityPolicy problems. I have decompiled ipa and tried several apps.

**Comment by leonjza** [comment]
Unfortunately there is not much more I can do. Feel free to comment if you have an idea why `setSSLPinningMode:` is missing for you. I won't discount the fact that some form of obfuscation may be in place where the method was renamed something.

In either case, manual work is necessary here.

**Comment by leonjza** [comment]
Good news! Just ran into an application with similar behaviour. Should be able to push a workaround later today. :)

**Comment by ldbfpiaoran** [comment]
@leonjza   thinks   the  problem  is solve. However ,  A new problem has arisen.  such as 


(agent) Hooking common framework methods
(agent) [627jtkbek3t] Found AFNetworking library. Hooking known pinning methods.
(agent) [627jtkbek3t] Found NSURLSession based classes. Hooking known pinning methods.
(agent) Hooking lower level SSL methods
(agent) Hooking lower level TLS methods
A Frida agent exception has occurred.
Error: expected a pointer
    at /script1.js:6275
    at /script1.js:6422
    at /script1.js:6427
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\commands\ios\pinning.py", line 26, in ios_disable
    api.ios_pinning_disable(_should_be_quiet(args))
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: expected a pointer
    at /script1.js:6275
    at /script1.js:6422
    at /script1.js:6427
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)



I think the problem is on frida\core.py. It seems that the reason for the error is the same. I am very annoyed that I am doing Android. I am not very familiar with ios. I can't help you. You can do it at http://i.meituan. .com/mobile/down/meituan There is no problem with the download attempt

**Comment by ldbfpiaoran** [comment]
@leonjza   But the ssl certificate has been bypassed

**Comment by leonjza** [comment]
Can you run objection with the `--debug` flag and paste the stack trace please?

**Comment by ldbfpiaoran** [comment]
- [incoming message] ------------------
{
  "payload": "\u001b[90mHooking common framework methods\u001b[39m",
  "type": "send"
}
- [./incoming message] ----------------
(agent) Hooking common framework methods
- [incoming message] ------------------
{
  "payload": "\u001b[90m[xoyrkxlm3kc] \u001b[39mFound AFNetworking library. Hooking known pinning methods.",
  "type": "send"
}
- [./incoming message] ----------------
(agent) [xoyrkxlm3kc] Found AFNetworking library. Hooking known pinning methods.
- [incoming message] ------------------
{
  "payload": "\u001b[90m[xoyrkxlm3kc] \u001b[39mFound NSURLSession based classes. Hooking known pinning methods.",
  "type": "send"
}
- [./incoming message] ----------------
(agent) [xoyrkxlm3kc] Found NSURLSession based classes. Hooking known pinning methods.
- [incoming message] ------------------
{
  "payload": "\u001b[90mHooking lower level SSL methods\u001b[39m",
  "type": "send"
}
- [./incoming message] ----------------
(agent) Hooking lower level SSL methods
- [incoming message] ------------------
{
  "payload": "\u001b[90mHooking lower level TLS methods\u001b[39m",
  "type": "send"
}
- [./incoming message] ----------------
(agent) Hooking lower level TLS methods
A Frida agent exception has occurred.
Error: expected a pointer
    at src/ios/lib/libobjc.ts:78
    at src/ios/pinning.ts:108
    at src/ios/pinning.ts:113
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objection\commands\ios\pinning.py", line 26, in ios_disable
    api.ios_pinning_disable(_should_be_quiet(args))
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\frida\core.py", line 322, in method
    return script._rpc_request('call', js_name, args)
  File "C:\Users\cjx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\frida\core.py", line 250, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: expected a pointer
    at src/ios/lib/libobjc.ts:78
    at src/ios/pinning.ts:108
    at src/ios/pinning.ts:113
    at frida/runtime/message-dispatcher.js:15
    at o (frida/runtime/message-dispatcher.js:25)
