### ISSUE TITLE
An error may have occurred while running aapt.

### ISSUE THREAD

**Issue by GGLPWR** [sensepost/objection#247]
```
An error may have occurred while running aapt.
/usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE

Injecting permission: android.permission.INTERNET
Writing new Android manifest...
Target class not specified, searching for launchable activity instead...
An error may have occurred while running aapt.
/usr/bin/aapt: symbol lookup error: /usr/lib/i386-linux-gnu/android/libaapt.so.0: undefined symbol: _ZN7android12AssetManagerC1ENS0_9CacheModeE

Unable to determine the launchable activity using aapt, trying to manually parse the AndroidManifest for activity aliases...
Unable to determine the launchable activity for this app.
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/objection/console/cli.py", line 342, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.7/dist-packages/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library(target_class=target_class)
  File "/usr/local/lib/python3.7/dist-packages/objection/utils/patchers/android.py", line 708, in inject_load_library
    target_class if target_class else self._get_launchable_activity())
  File "/usr/local/lib/python3.7/dist-packages/objection/utils/patchers/android.py", line 321, in _get_launchable_activity
    raise Exception('Unable to determine launchable activity')
Exception: Unable to determine launchable activity
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpwl3574g6.apktemp.objection.apk'
```

**Comment by leonjza** [comment]
Your `aapt` installation seems broken.
