### ISSUE TITLE
Patching IPA key error: tag_name

### ISSUE THREAD

**Issue by amagdaraog** [sensepost/objection#251]
Traceback (most recent call last):
  File "/Users/adrianemagdaraog/virtual-python3/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/objection/console/cli.py", line 307, in patchipa
    patch_ios_ipa(**locals())
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 37, in patch_ios_ipa
    github_version = github.get_latest_version()
  File "/Users/adrianemagdaraog/virtual-python3/lib/python3.7/site-packages/objection/utils/patchers/github.py", line 52, in get_latest_version
    self.gadget_version = self._call(self.GITHUB_LATEST_RELEASE)['tag_name']
KeyError: 'tag_name'

**Comment by leonjza** [comment]
Something went wrong with downloading from the Github API. Check your connection and keep in mind that Github has rate limits.

**Comment by amagdaraog** [comment]
Can actually patch now, but don't know when the count refreshes and how many.
