### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by fiestyqier** [sensepost/objection#260]
Hi,

I am getting `ModuleNotFoundError: No module named '_sqlite3'` when running command `objection`.

**Logs**

```
$ objection
Traceback (most recent call last):
  File "/Users/xx/env/py36/bin/objection", line 6, in <module>
    from objection.console.cli import cli
  File "/Users/xx/env/py36/lib/python3.6/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/Users/xx/env/py36/lib/python3.6/site-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/Users/xx/env/py36/lib/python3.6/site-packages/objection/console/commands.py", line 8, in <module>
    from ..commands import sqlite
  File "/Users/xx/env/py36/lib/python3.6/site-packages/objection/commands/sqlite.py", line 3, in <module>
    import sqlite3
  File "/Users/xx/opt/py36/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/Users/xx/opt/py36/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by leonjza** [comment]
This looks like a local installation issue. I would suggest you try and reinstall objection using the methods described in the wiki [here](https://github.com/sensepost/objection/wiki/Installation).

**Comment by tangxuesong6** [comment]
the same error:
```
Traceback (most recent call last):
  File "/home/txs/.pyenv/versions/fridaenv/bin/objection", line 11, in <module>
    load_entry_point('objection==1.9.4', 'console_scripts', 'objection')()
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/objection/console/commands.py", line 10, in <module>
    from ..commands import sqlite
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/objection/commands/sqlite.py", line 7, in <module>
    from litecli.main import LiteCli
  File "/home/txs/.pyenv/versions/3.8.2/envs/fridaenv/lib/python3.8/site-packages/litecli/main.py", line 13, in <module>
    from sqlite3 import OperationalError
  File "/home/txs/.pyenv/versions/3.8.2/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/txs/.pyenv/versions/3.8.2/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```
OS: debian9
