### ISSUE TITLE
Error when connecting 

### ISSUE THREAD

**Issue by harso2** [sensepost/objection#262]
**Describe the bug**
Iphone XS - jailbroken 12.1.2
Installed frida server - works fine when just the frida commands are used

**To Reproduce**
Try to connect

**Expected behavior**
Successful connection

**Evidence / Logs / Screenshots**
```
C:\Users\ALex>objection --network --host "192.168.1.119" explore
Using networked device @`192.168.1.119:27042`
Traceback (most recent call last):
  File "C:\Users\ALex\AppData\Local\Programs\Python\Python37\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.6.6', 'console_scripts', 'objection')()
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\objection\utils\agent.py", line 195, in inject
    session = self.get_session()
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\objection\utils\agent.py", line 159, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "c:\users\alex\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 98, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: unexpected error while starting thread (act_set_state returned '(os/kern) protection failure')
```
**Environment (please complete the following information):**
 - Device: Iphone XS
 - OS: 12.1.2 - jailbroken
 - Frida Version - latest
- Objection Version - latest

**Additional context**
The server is up and running on the phone and accessible, objection just encounters errors when trying to spawn

**Comment by leonjza** [comment]
How are you starting the `frida` command line?
