### ISSUE TITLE
Unable to patch IPA - Mojave

### ISSUE THREAD

**Issue by unl1k3ly** [sensepost/objection#265]
**Describe the bug**
Hi mate, thanks for the awesome work! Really !
I've been trying to patch an IPA and it seems I'm stuck in an error i can't get pass, wondering if you know something that could help me move along.
 
I've tried with many IPA i have here, same error :/

Ideas ?

Thank you so much.

**To Reproduce**
```
 v@Viniciuss-MBP  ~/Downloads  objection patchipa --source DamnVulnerableiOSApp.ipa --codesign-signature 50D1D4ED02AEA0E572BFC4F243A8A5B44659B26F                                         ✔  4623  21:41:07
Using latest Github gadget version: 12.6.13
Patcher will be using Gadget version: 12.6.13
No provision file specified, searching for one...
No provisioning files found. Please specify one or generate one by building an app.
Working with app: DamnVulnerableIOSApp.app
Bundle identifier is: com.highaltitudehacks.dvia
Creating Frameworks directory for FridaGadget...
Codesigning 1 .dylib's with signature 50D1D4ED02AEA0E572BFC4F243A8A5B44659B26F
Code signing: FridaGadget.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Traceback (most recent call last):
  File "/Users/v/Downloads/virtual-python3/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/objection/console/cli.py", line 307, in patchipa
    patch_ios_ipa(**locals())
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 70, in patch_ios_ipa
    patcher.archive_and_codesign(original_name=source, codesign_signature=codesign_signature)
  File "/Users/v/Downloads/virtual-python3/lib/python3.7/site-packages/objection/utils/patchers/ios.py", line 415, in archive_and_codesign
    self.patched_ipa_path
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 530, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/9k/8nnpkzms4_v_15j7lvqfrdd80000gn/T/DamnVulnerableiOSApp-frida-codesigned.ipa'
```

**Environment (please complete the following information):**
 - OS: Mojave
 - Frida Version [e.g. 22]
- Objection Version [e.g. 1.7.0]

**Comment by unl1k3ly** [comment]
Fixed it myself! Problem was due the fact that I had provisioning the app to a virtual phone rather than a physically device. it's working now! Thanks
