### ISSUE TITLE
Exception: Unable to determine URL for iOS gadget download

### ISSUE THREAD

**Issue by merkader69** [sensepost/objection#28]
**# **Tried this on Kali Linux aswell as win10. Same result on both. I'm pretty new to this, but I decided to check the source code and really had no idea. What's going on exactly? Phone is a Google Pixel on 8.0****

```
C:\Users\calib>objection patchapk  --source C:\Users\calib\Desktop\base.apk
No architecture specified. Determining it using `adb`...
Detected the architecture as: arm64-v8a
Github FridaGadget is v10.6.7, local is v0. Updating...
Unable to determine URL to download the library
Traceback (most recent call last):
  File "C:\Users\calib\AppData\Local\Programs\Python\Python36\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.1.10', 'console_scripts', 'objection')()
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\objection\console\cli.py", line 181, in patchapk
    patch_android_apk(**locals())
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\objection\commands\mobile_packages.py", line 108, in patch_android_apk
    android_gadget.download() \
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\objection\utils\packages.py", line 721, in download
    download_url = self._get_download_url()
  File "c:\users\calib\appdata\local\programs\python\python36\lib\site-packages\objection\utils\packages.py", line 756, in _get_download_url
    raise Exception('Unable to determine URL for iOS gadget download.')
Exception: Unable to determine URL for iOS gadget download.

```

**Comment by leonjza** [comment]
Thanks for the report! Apart from the fact that the wrong message is shown in the exception that is thrown (sorry about that I'll fix it), it seems like the latest release of Frida is missing the Android frida-gadgets for versions [10.6.6](https://github.com/frida/frida/releases/tag/10.6.6) and [10.6.7](https://github.com/frida/frida/releases/tag/10.6.7). I've pinged the Frida guys about this quickly and hopefully it will get sorted asap.

In the mean time I will work something out for objection to handle this scenario better in the future. Maybe add a flag that lets you specify the gadget version you want to use.

Will update when I have more!

**Comment by leonjza** [comment]
The Android `frida-gadget` for 10.6.7 is available now. Could you retry the patching process?

**Comment by merkader69** [comment]
Yep, it's fixed! Thanks man!

**Comment by rustymagnet3000** [comment]
I hit the same.  Better to use the: `--gadget-version 10.7.5` flag
