### ISSUE TITLE
ImportError: cannot import name 'FuzzyCompleter'

### ISSUE THREAD

**Issue by mpgn** [sensepost/objection#290]
**Describe the bug**
`ImportError: cannot import name 'FuzzyCompleter'`

**To Reproduce**
```
⋊> ~ pip3 install objection --user                                                                                                                                         12:54:07
Requirement already satisfied: objection in ./.local/lib/python3.6/site-packages (1.6.4)
Requirement already satisfied: prompt-toolkit<3.0.0,>=2.0.0 in ./.local/lib/python3.6/site-packages (from objection) (2.0.7)
Requirement already satisfied: frida-tools in ./.local/lib/python3.6/site-packages (from objection) (2.0.1)
Requirement already satisfied: frida in ./.local/lib/python3.6/site-packages (from objection) (12.6.1)
Requirement already satisfied: delegator.py in ./.local/lib/python3.6/site-packages (from objection) (0.1.1)
Requirement already satisfied: tabulate in ./.local/lib/python3.6/site-packages (from objection) (0.8.3)
Requirement already satisfied: requests in ./.local/lib/python3.6/site-packages (from objection) (2.20.0)
Requirement already satisfied: flask in ./.local/lib/python3.6/site-packages (from objection) (1.0.2)
Requirement already satisfied: click in ./.local/lib/python3.6/site-packages (from objection) (7.0)
Requirement already satisfied: six>=1.9.0 in ./.local/lib/python3.6/site-packages (from prompt-toolkit<3.0.0,>=2.0.0->objection) (1.10.0)
Requirement already satisfied: wcwidth in ./.local/lib/python3.6/site-packages (from prompt-toolkit<3.0.0,>=2.0.0->objection) (0.1.7)
Requirement already satisfied: pygments<3.0.0,>=2.0.2 in ./.local/lib/python3.6/site-packages (from frida-tools->objection) (2.3.0)
Requirement already satisfied: colorama<1.0.0,>=0.2.7 in ./.local/lib/python3.6/site-packages (from frida-tools->objection) (0.4.1)
Requirement already satisfied: pexpect>=4.1.0 in ./.local/lib/python3.6/site-packages (from delegator.py->objection) (4.6.0)
Requirement already satisfied: idna<2.8,>=2.5 in ./.local/lib/python3.6/site-packages (from requests->objection) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python3.6/site-packages (from requests->objection) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->objection) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->objection) (1.22)
Requirement already satisfied: Jinja2>=2.10 in ./.local/lib/python3.6/site-packages (from flask->objection) (2.10.1)
Requirement already satisfied: itsdangerous>=0.24 in ./.local/lib/python3.6/site-packages (from flask->objection) (1.1.0)
Requirement already satisfied: Werkzeug>=0.14 in ./.local/lib/python3.6/site-packages (from flask->objection) (0.14.1)
Requirement already satisfied: ptyprocess>=0.5 in ./.local/lib/python3.6/site-packages (from pexpect>=4.1.0->delegator.py->objection) (0.6.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python3.6/site-packages (from Jinja2>=2.10->flask->objection) (1.1.0)
WARNING: You are using pip version 19.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
⋊> ~ objection                                                                                                                                                             12:54:18
Traceback (most recent call last):
  File "/home/bonclay/.local/bin/objection", line 6, in <module>
    from objection.console.cli import cli
  File "/home/bonclay/.local/lib/python3.6/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/home/bonclay/.local/lib/python3.6/site-packages/objection/console/repl.py", line 10, in <module>
    from prompt_toolkit.completion import FuzzyCompleter
ImportError: cannot import name 'FuzzyCompleter'
```

**Comment by leonjza** [comment]
It looks like you are getting version `1.6.4` for some reason. Try adding the `--upgrade` flag?

**Comment by mpgn** [comment]
damm ! <3
