### ISSUE TITLE
iOS - Unable to determine URL to download the dylib

### ISSUE THREAD

**Issue by Blueeyes3** [sensepost/objection#304]
Hi Team, 

I am trying to patch ipa file with command objection patchipa --source test.ipa --codesign-signature value and I am facing the below error.

Using latest Github gadget version: 12.7.26
Remote FridaGadget version is v12.7.26, local is v12.7.24. Downloading...
Unable to determine URL to download the dylib
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/objection", line 11, in <module>
    load_entry_point('objection==1.8.3', 'console_scripts', 'objection')()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/console/cli.py", line 309, in patchipa
    patch_ios_ipa(**locals())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 51, in patch_ios_ipa
    ios_gadget.download() \
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/utils/patchers/ios.py", line 65, in download
    download_url = self._get_download_url()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/objection/utils/patchers/ios.py", line 100, in _get_download_url
    raise Exception('Unable to determine URL for iOS gadget download.')
Exception: Unable to determine URL for iOS gadget download.

Please assist.

Thanks in advance!

**Comment by leonjza** [comment]
Looks like there is an issue with the latest release where all of the assets are not available. 12.7.25 has 115 assets and 12.7.26 only 61, missing the gadget which you need. For now you can just specify the version to use as 12.7.25 until that is sorted.

**Comment by Blueeyes3** [comment]
That helped! . Thanks @leonjza :)

**Comment by leonjza** [comment]
12.7.26 release of Frida should have all of the assets again.

**Comment by san3ncrypt3d** [comment]
Hey guys,

Im having the same issue:
objection patchipa -s m.ipa -c 5xxxxx6

Using latest Github gadget version: 12.8.16
Remote FridaGadget version is v12.8.16, local is v0. Downloading...
Unable to determine URL to download the dylib
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/objection/console/cli.py", line 309, in patchipa
    patch_ios_ipa(**locals())
  File "/usr/local/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 51, in patch_ios_ipa
    ios_gadget.download() \
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/ios.py", line 65, in download
    download_url = self._get_download_url()
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/ios.py", line 100, in _get_download_url
    raise Exception('Unable to determine URL for iOS gadget download.')
Exception: Unable to determine URL for iOS gadget download.



How do i specify version for frida ?
please advise
