### ISSUE TITLE
unable to communicate with remote frida-server

### ISSUE THREAD

**Issue by vincentcox** [sensepost/objection#31]
I used the command `objection explore`on mac (10.12.6 (16G29)). It got me the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 83, in explore
    device_info = get_device_info()
  File "/usr/local/lib/python3.6/site-packages/objection/commands/device.py", line 20, in get_device_info
    runner.run(hook=hook)
  File "/usr/local/lib/python3.6/site-packages/objection/utils/frida_transport.py", line 341, in run
    session = self.get_session()
  File "/usr/local/lib/python3.6/site-packages/objection/utils/frida_transport.py", line 282, in get_session
    return frida.get_usb_device(5).attach(state_connection.gadget_name)
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 97, in attach
    return Session(self._impl.attach(self._pid_of(target)))
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 115, in _pid_of
    return self.get_process(target).pid
  File "/usr/local/lib/python3.6/site-packages/frida/core.py", line 67, in get_process
    matching = [process for process in self._impl.enumerate_processes() if fnmatch.fnmatchcase(process.name.lower(), process_name_lc)]
frida.ProtocolError: unable to communicate with remote frida-server; please ensure that major versions match and that the remote Frida has the feature you are trying to use
```

Any idea what went wrong? The versions don't match is weird because we just build the application with the tool.

**Comment by vincentcox** [comment]
Solved it by upgrading frida in cydia.
