### ISSUE TITLE
memory search:frida.core.RPCException: Error: access violation accessing 0x7f4902b000

### ISSUE THREAD

**Issue by liangshinian** [sensepost/objection#326]
**Describe the bug**
when i was run "memory search xxxx --string" for a rooted android device, it throw an exception.

```
A Frida agent exception has occurred.
Error: access violation accessing 0x7f4902b000
    at /script1.js:9878
    at map (native)
    at /script1.js:9885
    at frida/runtime/message-dispatcher.js:15
    at c (frida/runtime/message-dispatcher.js:25)

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/site-packages/objection/commands/memory.py", line 247, in find_pattern
    data = api.memory_search(pattern, _should_only_dump_offsets(args))
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 333, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: access violation accessing 0x7f4902b000
    at /script1.js:9878
    at map (native)
    at /script1.js:9885
    at frida/runtime/message-dispatcher.js:15
    at c (frida/runtime/message-dispatcher.js:25)
```

**To Reproduce**
1. objection --gadget "xxxxx" explore
2. memory search xxxx --string

**Environment (please complete the following information):**
 - Device: [android6.0]
 - Frida Version [12.8.11]
- Objection Version [1.8.4]

**Comment by leonjza** [comment]
Unfortunately this command can be a little racy where the address when enumerated has since been remapped when trying to access it, resulting in errors such as these.

**Comment by guillaumelh** [comment]
Thank @leonjza . Do you have an idea of how I can overcome this issue ?
