### ISSUE TITLE
Failed to determine device type !

### ISSUE THREAD

**Issue by Githubplay12** [sensepost/objection#33]
So I installed objection (pip install objection) , installed virtualenv (and all the prequesites) 
ran : objection --gadget frida-server explore 
and everytime I get failed to determine device type, I'm on windows 7 if that means anything.

frida-ps -U works well so it's not from frida 

```
(C:\Users\CARBON\Anaconda3) C:\Windows\system32>objection
Usage: objection [OPTIONS] COMMAND [ARGS]...

       _     _         _   _
   ___| |_  |_|___ ___| |_|_|___ ___
  | . | . | | | -_|  _|  _| | . |   |
  |___|___|_| |___|___|_| |_|___|_|_|
          |___|(object)inject(ion)

       Runtime Mobile Exploration
          by: @leonjza from @sensepost

  By default, communications will happen over USB, unless the --network
  option is provided.

Options:
  -N, --network       Connect using a network connection instead of USB.
                      [default: False]
  -h, --host TEXT     [default: 127.0.0.1]
  -p, --port INTEGER  [default: 27042]
  -g, --gadget TEXT   Name of the Frida Gadget/Process to connect to.
                      [default: Gadget]
  --help              Show this message and exit.

Commands:
  device_type  Get information about an attached device.
  explore      Start the objection exploration REPL.
  patchapk     Patch an APK with the frida-gadget.so.
  patchipa     Patch an IPA with the FridaGadget dylib.
  run          Run a single objection command.
  version      Prints the current version and exists.

(C:\Users\CARBON\Anaconda3) C:\Windows\system32>objection --gadget frida-server
device_type
[hook failure] Unknown Platform
Failed to determine device type!
Traceback (most recent call last):
  File "c:\users\carbon\anaconda3\lib\runpy.py", line 193, in _run_module_as_mai
n
    "__main__", mod_spec)
  File "c:\users\carbon\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\CARBON\Anaconda3\Scripts\objection.exe\__main__.py", line 9, in
 <module>
  File "c:\users\carbon\anaconda3\lib\site-packages\click\core.py", line 722, in
 __call__
    return self.main(*args, **kwargs)
  File "c:\users\carbon\anaconda3\lib\site-packages\click\core.py", line 697, in
 main
    rv = self.invoke(ctx)
  File "c:\users\carbon\anaconda3\lib\site-packages\click\core.py", line 1066, i
n invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\carbon\anaconda3\lib\site-packages\click\core.py", line 895, in
 invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\carbon\anaconda3\lib\site-packages\click\core.py", line 535, in
 invoke
    return callback(*args, **kwargs)
  File "c:\users\carbon\anaconda3\lib\site-packages\objection\console\cli.py", l
ine 145, in device_type
    device_name, system_name, model, system_version = get_device_info()
  File "c:\users\carbon\anaconda3\lib\site-packages\objection\commands\device.py
", line 28, in get_device_info
    raise Exception(msg)
Exception: Failed to determine device type!
```

**Comment by leonjza** [comment]
Based on your command line arguments, you are connecting to the `frida-server` process which is Frida itself. objection runs a bunch of run time specific hooks on startup for mobile apps to get device / app related data, which might not be available in the `frida-server` process. Try connecting to an application you have running on your phone instead. You can pick one from the list output with `frida-ps -U`.

**Comment by Githubplay12** [comment]
Ok will try and get back to you, thanks for the help :)

**Comment by leonjza** [comment]
Closing this for now. Feel free to update if there are any other issues!
