### ISSUE TITLE
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpg1sejndy.apktemp.objection.apk' 

### ISSUE THREAD

**Issue by kychanbp** [sensepost/objection#330]
```
ebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
brut.directory.PathNotExist: apktool.yml                                             
                                                                                     
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 10, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/johnchan/.local/lib/python3.7/site-packages/objection/console/cli.py", line 352, in patchapk
    patch_android_apk(**locals())
  File "/home/johnchan/.local/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 187, in patch_android_apk
    patcher.build_new_apk(use_aapt2=use_aapt2)
  File "/home/johnchan/.local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 782, in build_new_apk
    self._copy_meta_inf()
  File "/home/johnchan/.local/lib/python3.7/site-packages/objection/utils/patchers/android.py", line 788, in _copy_meta_inf
    extra_names = list(itertools.filterfalse(standard_files.match, os.listdir(meta_inf)))
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpg1sejndy.apktemp/original/META-INF'
```

**Comment by leonjza** [comment]
Like the error says, app rebuilding failed. This is an `apktool` error. This is something you will need to manually inspect/fix.
