### ISSUE TITLE
[bug] unable to handle 64-bit processes due to build configuration

### ISSUE THREAD

**Issue by Techbrunch** [sensepost/objection#354]
**Describe the bug**

When importing a script objection throw an error. I'll add more info about the script later. Note that the script appear to run successfully.

**To Reproduce**

```text
com.company.app on (google: 7.0) [usb] # import /tmp/compiled.js
```

**Expected behavior**

No errors in logs.

**Evidence / Logs / Screenshots**

```text
com.company.app on (google: 7.0) [usb] # import /tmp/compiled.js
[debug] Loading a background script
[*] Injected a test script (this runs from within the injected application)!
classInformation: 0x7d551b58
'modify_function_argument.js' attached and ready.
[debug] Resuming PID `8255`
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
unable to handle 64-bit processes due to build configuration

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.7/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.7/site-packages/objection/commands/frida_commands.py", line 71, in load_background
    agent.background(hook)
  File "/usr/local/lib/python3.7/site-packages/objection/utils/agent.py", line 274, in background
    self.device.resume(self.spawned_pid)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.NotSupportedError: unable to handle 64-bit processes due to build configuration
```

**Environment (please complete the following information):**
 - Device: Emulator AVD
 - OS: Android API 24
 - Frida Version 12.8.19
- Objection Version v1.9.0

**Comment by leonjza** [comment]
Could you try and run it using vanilla `frida` with `frida -U com.company.app -l /tmp/compiled.js` ?

**Comment by Techbrunch** [comment]
Hum I can't reproduce it with Frida 12.8.20, I closing this for now, sorry.
