### ISSUE TITLE
[bug] Exception in thread Thread-13 when unpacking

### ISSUE THREAD

**Issue by bradk15** [sensepost/objection#372]
I'm getting an Exception in thread Thread-13 when attempting to patch using objection 

The output from objection is below. It appears I can use apktool separately on the apk without issue.

```
C:\adb>objection patchapk -s base.apk --skip-resources
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 12.8.20
Patcher will be using Gadget version: 12.8.20
Detected apktool version as: 2.4.1
Running apktool empty-framework-dir...
I: Removing 1.apk framework file...
Press any key to continue . . .
Unpacking base.apk
Exception in thread Thread-13:
Traceback (most recent call last):
  File "c:\users\username\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\username\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\username\appdata\local\programs\python\python38\lib\subprocess.py", line 1366, in _readerthread
    buffer.append(fh.read())
  File "c:\users\username\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6051: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.2', 'console_scripts', 'objection')()
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\objection\console\cli.py", line 366, in patchapk
    patch_android_apk(**locals())
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\objection\commands\mobile_packages.py", line 189, in patch_android_apk
    patcher.inject_internet_permission(skip_resources=skip_resources)
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\objection\utils\patchers\android.py", line 423, in inject_internet_permission
    if internet_permission in self._get_appt_output():
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\objection\utils\patchers\android.py", line 294, in _get_appt_output
    o = delegator.run(self.list2cmdline([
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\delegator.py", line 320, in run
    c.block()
  File "c:\users\username\appdata\local\programs\python\python38\lib\site-packages\delegator.py", line 238, in block
    stdout, stderr = self.subprocess.communicate()
  File "c:\users\username\appdata\local\programs\python\python38\lib\subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "c:\users\username\appdata\local\programs\python\python38\lib\subprocess.py", line 1416, in _communicate
    stdout = stdout[0]
IndexError: list index out of range
Cleaning up temp files...
Failed to cleanup with error: [WinError 2] The system cannot find the file specified: 'C:\\Users\\username\\AppData\\Local\\Temp\\tmp3wt_jyee.apktemp.objection.apk'
```

**Comment by bradk15** [comment]
I did attempt this under the Ubuntu Windows app and it worked fine, so maybe something with my Windows configuration?

**Comment by leonjza** [comment]
Looks like the issue here:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6051: character maps to <undefined>
```

I have no idea what it means. Does your application have non unicode characters in the name, or maybe some strange activity names as a result of obfuscation?

**Comment by h1pmnh** [comment]
In case anyone else finds this like I did from a Google search, you can set the `PYTHONUTF8=1` environment variable before running Objection to default Python on Windows to the UTF-8 character set instead of cp1252 (ref: [PEP-540](https://peps.python.org/pep-0540/)). You will hit this issue in Objection on Windows if you're working with APKs that contain UTF-8 characters in certain files or fields.

Hope that helps someone in the future!
