### ISSUE TITLE
Objection facing issues with multiprocessing (No command working)

### ISSUE THREAD

**Issue by ishan-saha** [sensepost/objection#386]
After installing objection in MacOS 10.15 with python 3.8, it starts to throw an error regarding the multiprocessing. Any objection command that is run give the same error. 

1. install objection
2. Run objection commands (all give the same error) 

Error: 
```Ishans-MacBook-Air:~ ishan$ objection
Usage: objection [OPTIONS] COMMAND [ARGS]...

       _   _         _   _
   ___| |_|_|___ ___| |_|_|___ ___
  | . | . | | -_|  _|  _| | . |   |
  |___|___| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion)
  
       Runtime Mobile Exploration
          by: @leonjza from @sensepost

  By default, communications will happen over USB, unless the --network
  option is provided.

Options:
  -N, --network            Connect using a network connection instead of USB.
                           [default: False]

  -h, --host TEXT          [default: 127.0.0.1]
  -p, --port INTEGER       [default: 27042]
  -ah, --api-host TEXT     [default: 127.0.0.1]
  -ap, --api-port INTEGER  [default: 8888]
  -g, --gadget TEXT        Name of the Frida Gadget/Process to connect to.
                           [default: Gadget]

  -S, --serial TEXT        A device serial to connect to.
  -d, --debug              Enable debug mode with verbose output. (Includes
                           agent source map in stack traces)

  --help                   Show this message and exit.

Commands:
  api          Start the objection API server in headless mode.
  device-type  Get information about an attached device.
  explore      Start the objection exploration REPL.
  patchapk     Patch an APK with the frida-gadget.so.
  patchipa     Patch an IPA with the FridaGadget dylib.
  run          Run a single objection command.
  version      Prints the current version and exists.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/objection-1.9.5-py3.8.egg/objection/utils/__init__.py", line 57, in <module>
    Process(target=check_version).start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Ishans-MacBook-Air:~ ishan$ 
```

Environment:
 - Device: [ iPhone6 12.4 ]
 - OS: [ iOS 10.15.5 ]
 - Frida Version [ 12 ] 
 - Python [ 3.8 ]

**Comment by saraivamarco** [comment]
Try with python2, I also had issues with python3 and this solution worked
for me.

**Comment by leonjza** [comment]
We recently made a change to how the update checker works to fix #381, but it looks like it's causing more problems than fixing now. Thanks for the report!

**Comment by ishan-saha** [comment]
You could use some sort of try catch and finally statements for this ..... the problem is because freeze_support() is only for windows and is not working on mac or ubuntu(just checked on ubuntu LTS 18).

**Comment by sleeyax** [comment]
I'm having the same issue on Windows 10, Python 3.7.0.

**Comment by leonjza** [comment]
Sorry I have been pretty swamped at the moment, but realise this needs to be fixed quickly. I'll get to it asap!

**Comment by AngeloD2022** [comment]
@leonjza Getting this error as well. No rush! :)

**Comment by kevinspider** [comment]
macos: 10.15.4 (19E266)
python: 3.7.7
pip: 20.1.1
objection 1.9.1 
I try it can use..

**Comment by leonjza** [comment]
I have refactored the updater a bit in https://github.com/sensepost/objection/commit/bca97762497783e8cc5929b4dd4c32427316d4c9 if anyone wants to give it a try before I land it in a release.

**Comment by Slayer741** [comment]
Gave it a try and works like a charm, thanks for the heads up
Python v3.8

**Comment by leonjza** [comment]
1.9.6 just landed with this fix.
