### ISSUE TITLE
[Error] Error when patching IPA

### ISSUE THREAD

**Issue by egegrsn** [sensepost/objection#423]
Hello there,

Firstly, thanks for the great effort you've put. Although I checked similar errors and tried their solutions, I still could not fix the issue. When I try to patch it gives me an error:

objection patchipa --source deneme.ipa --codesign-signature xxxxxxxx

```
Copying final ipa from /var/folders/9g/0rzlghr55ts1l964k9mbhgnh0000gn/T/deneme-frida-codesigned.ipa to current directory...
Traceback (most recent call last):
  File "/Users/egegirsen/opt/anaconda3/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/objection/console/cli.py", line 315, in patchipa
    patch_ios_ipa(**locals())
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/site-packages/objection/commands/mobile_packages.py", line 92, in patch_ios_ipa
    shutil.copyfile(
  File "/Users/egegirsen/opt/anaconda3/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/9g/0rzlghr55ts1l964k9mbhgnh0000gn/T/deneme-frida-codesigned.ipa'
Cleaning up temp files...
**Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/9g/0rzlghr55ts1l964k9mbhgnh0000gn/T/deneme-frida-codesigned.ipa'
```

**Similar issues**
#286 

Any help will be much appreciated.

**Comment by leonjza** [comment]
Unfortunately this stack trace is incomplete.
