### ISSUE TITLE
[bug] frida.TransportError: timeout was reached when using Identifier instead of PID on iOS 13.7

### ISSUE THREAD

**Issue by blincoln-bf** [sensepost/objection#433]
**Describe the bug**
I am running Frida and Objection on a Windows 10 system against an iOS 13.7 device jailbroken using Odyssey. If I attempt to use a basic _objection explore_ command or connect to a process using its identifier, the attempt times out, e.g.:

```
PS C:\WINDOWS\system32> frida-ps -Uia
 PID  Name           Identifier
----  -------------  -----------------------------------------------
1033  AltStore       com.REDACTED.com.rileytestut.AltStore
 695  Settings       com.apple.Preferences
 713  Sileo          org.coolstar.SileoStore

PS C:\WINDOWS\system32> objection -g org.coolstar.SileoStore explore
Using USB device `Apple iPhone`
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "c:\program files\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TransportError: timeout was reached
```

Nearly all of the Objection docs use this syntax, but after quite a bit of searching around, I discovered that it supports using the numeric PID instead, and that succeeds, e.g.:

```
PS C:\WINDOWS\system32> objection -g 695 explore
Using USB device `Apple iPhone`
Agent injected and responds ok!

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.9.6

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.apple.Preferences on (iPhone: 13.7) [usb] # exit
Exiting...
Asking jobs to stop...
Unloading objection agent...
```

**To Reproduce**
1. Run command 'frida-ps -Uia' and find some Identifiers and PIDs
2. Run command 'objection -g org.coolstar.SileoStore explore' or another running app by Identifier. Notice that Objection times out.
3. Run command 'objection -g 12345 explore', replacing '12345' with a valid PID. Notice that Objection connects.

**Similar issues**
https://github.com/sensepost/objection/issues/46 is where I found the reference to using the PID instead.

**Expected behavior**
Objection should inject successfully into the process

**Evidence / Logs / Screenshots**

```
PS C:\WINDOWS\system32> frida-ps -Uia
 PID  Name           Identifier
----  -------------  -----------------------------------------------
1033  AltStore       com.REDACTED.com.rileytestut.AltStore
 695  Settings       com.apple.Preferences
 713  Sileo          org.coolstar.SileoStore

PS C:\WINDOWS\system32> objection -g com.apple.Preferences --debug explore
[debug] Agent path is: c:\program files\python38\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Apple iPhone`
[debug] Attempting to attach to process: `com.apple.Preferences`
[debug] Unable to find process: `com.apple.Preferences`, attempting spawn
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "c:\program files\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TransportError: timeout was reached
```

```
PS C:\WINDOWS\system32> objection -g Sileo --debug explore
[debug] Agent path is: c:\program files\python38\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Apple iPhone`
[debug] Attempting to attach to process: `Sileo`
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "c:\program files\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 152, in get_session
    self.session = self.device.attach(state_connection.gadget_name)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.ProtocolError: timeout was reached
```

```
PS C:\WINDOWS\system32> objection -g Settings --debug explore
[debug] Agent path is: c:\program files\python38\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Apple iPhone`
[debug] Attempting to attach to process: `Settings`
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "c:\program files\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 152, in get_session
    self.session = self.device.attach(state_connection.gadget_name)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.TransportError: timeout was reached
```

```
PS C:\WINDOWS\system32> objection -g 695 --debug explore
[debug] Agent path is: c:\program files\python38\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Apple iPhone`
[debug] Attempting to attach to process: `695`
[debug] Process attached!
Agent injected and responds ok!

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.9.6

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.apple.Preferences on (iPhone: 13.7) [usb] #
```

I don't have a --debug version of this one, sorry. Can't rerun it without rebooting the device, and I don't want to have to jailbreak it again:

```
PS C:\WINDOWS\system32> objection explore
Using USB device `Apple iPhone`
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "c:\program files\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\program files\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\program files\python38\lib\site-packages\objection\utils\agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\program files\python38\lib\site-packages\frida\core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.TransportError: timeout was reached
```

**Environment (please complete the following information):**
 - Device: iPhone SE (original, from 2016)
 - OS: iOS 13.7
 - Frida Version 14.1.3
- Objection Version 1.9.6

**Application**
This happens with all apps on the device.

**Comment by leonjza** [comment]
While I am not sure what is happening here, I know the spawning logic needs some love. Going to close (and reference) this ticket in favour of #456 .

**Comment by kanadeblisst** [comment]
I have the same problem, but my device is oneplus3 and android pie .
Interestingly, when Windows runs objection, everything is normal, but Kali have this problem
