### ISSUE TITLE
[bug] patchapk fails on simple apk made with android studio

### ISSUE THREAD

**Issue by RobertoD91** [sensepost/objection#436]
**Describe the bug**
Made a simple android app with Android Studio, just the "Basic Activity" template and tried to inject gadgets with objection.

**To Reproduce**
Open Android studio, new project, select "basic activity" as template, then build apk (attached to this post)

`objection patchapk --source app-debug.apk --architecture armeabi-v7a`

**Evidence / Logs / Screenshots**

```text
xxxx@xxxx:~/AndroidStudioProjects/TestActivity$ objection --debug patchapk --source app-debug.apk --architecture armeabi-v7a
Using latest Github gadget version: 14.2.2
Patcher will be using Gadget version: 14.2.2
Detected apktool version as: 2.5.0
Running apktool empty-framework-dir...
I: Removing 1.apk framework file...
Unpacking it.xxx.testactivity_v0.apk
App does not have android.permission.INTERNET, attempting to patch the AndroidManifest.xml...
Injecting permission: android.permission.INTERNET
Writing new Android manifest...
Target class not specified, searching for launchable activity instead...
Reading smali from: /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/smali/it/xxx/testactivity/MainActivity.smali
Injecting loadLibrary call at line: 6
Attempting to fix the constructors .locals count
Current locals value is 0, updating to 1:
Writing patched smali back to: /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/smali/it/xxx/testactivity/MainActivity.smali
Creating library path: /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/lib/armeabi-v7a
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

W: invalid resource directory name: /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/res navigation
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/brut_util_Jar_7650119417360579723130066130800918824.tmp, p, --forced-package-id, 127, --min-sdk-version, 19, --target-sdk-version, 30, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/APKTOOL8294840959589313447.tmp, -e, /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/APKTOOL6743313661840483063.tmp, -0, arsc, -I, /Users/Roberto/Library/apktool/framework/1.apk, -S, /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/res, -M, /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp/AndroidManifest.xml]

Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signing the new APK may have failed.
jarsigner: unable to open jar file: /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp.objection.apk


Signed the new APK
Performing zipalign
Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error: 

Unable to open '/var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp.objection.apk' as zip archive

Zipalign completed
Copying final apk from /var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp.aligned.objection.apk to it.xxx.testactivity_v0.objection.apk in current directory...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/objection/console/cli.py", line 370, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.9/site-packages/objection/commands/mobile_packages.py", line 227, in patch_android_apk
    shutil.copyfile(patcher.get_patched_apk_path(), os.path.join(os.path.abspath('.'), destination))
  File "/usr/local/Cellar/python@3.9/3.9.1_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp.aligned.objection.apk'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/97/m6t3ncd55gzgjv_143f78fc00000gn/T/tmp4k7_g5ip.apktemp.objection.apk'
```

**Environment (please complete the following information):**
 - macOS 11.1
 - Frida Version 14.2.2
 - Objection Version 1.9.6

**Application**
View attach
[app-debug.apk.zip](https://github.com/sensepost/objection/files/5754876/app-debug.apk.zip)

**Comment by leonjza** [comment]
I wrote some content about debugging patching in wiki [here](https://github.com/sensepost/objection/wiki/Android-APK-Patching) a while ago. Please try those first, (and many of the other flags available on the `patchapk` command).

**Comment by RobertoD91** [comment]
Thanks, it works
- added `--skip-resources --ignore-nativelibs` flags
- added "android.permission.INTERNET" permission from android studio (required by `--skip-resources` flag)
