### ISSUE TITLE
[bug] Objection can not run on android11

### ISSUE THREAD

**Issue by viewZz** [sensepost/objection#441]
android 11 pixel4xl  frida12.10.4/14.1.0 frida-tools 8.1.3  objection 1.9.6/1.9.0/1.8.4
Hi,when i run objection on android 11 ,it did not start and throw some errors :
C:\Users\Administrator>objection -g com.example explore
Using USB device `Pixel 4 XL`
Agent injected and responds ok!
Traceback (most recent call last):
  File "D:\WindowsSecurityTools\python 3.8\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.9.6', 'console_scripts', 'objection')()
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\objection\console\cli.py", line 156, in explore
    device_info = get_device_info()
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\objection\commands\device.py", line 41, in get_device_info
    package_info = api.env_android()
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\frida\core.py", line 401, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "d:\windowssecuritytools\python 3.8\lib\site-packages\frida\core.py", line 333, in _rpc_request
    raise result[2]
frida.core.RPCException: Error: access violation accessing 0x51
    at frida/runtime/core.js:144
    at frida/node_modules/frida-java-bridge/lib/android.js:331
    at frida/node_modules/frida-java-bridge/lib/vm.js:11
    at Ve (frida/node_modules/frida-java-bridge/lib/android.js:346)
    at frida/node_modules/frida-java-bridge/lib/memoize.js:6
    at o (frida/node_modules/frida-java-bridge/lib/class-model.js:67)
    at _ (frida/node_modules/frida-java-bridge/lib/class-model.js:57)
    at frida/node_modules/frida-java-bridge/lib/class-model.js:8
    at frida/node_modules/frida-java-bridge/lib/class-factory.js:131
    [...]
Asking jobs to stop...
Unloading objection agent...

How to fix it?

**Comment by leonjza** [comment]
This may be app specific. Can you try using vanilla Frida first?

**Comment by viewZz** [comment]
> This may be app specific. Can you try using vanilla Frida first?
when I use android 7.1.2 nexus6P frida 12.10.4  objection 1.9.6 ,objection can run with this app
and I do not know the vanilla frida,can you post a url of  it

**Comment by leonjza** [comment]
The best place would be the Frida [documentation](https://frida.re/docs/quickstart/). For the command you are running `frida -U com.example` should drop you into a Frida repl.

**Comment by viewZz** [comment]
> The best place would be the Frida [documentation](https://frida.re/docs/quickstart/). For the command you are running `frida -U com.example` should drop you into a Frida repl.

I fix this issue. objection's crash may be caused by some app ruuning in the background  having two-process protection and anti-frida.

**Comment by leonjza** [comment]
👍
