### ISSUE TITLE
Unpacking  apk

### ISSUE THREAD

**Issue by shaohongwu** [sensepost/objection#446]
我在使用的时候出现以下问题

```
Unpacking base.apk                                                                                                            
Exception in thread Thread-10:                                                                                                
Traceback (most recent call last):                                                                                            
  File "d:\soft\anaconda3\lib\threading.py", line 932, in _bootstrap_inner                                                    
    self.run()                                                                                                                
  File "d:\soft\anaconda3\lib\threading.py", line 870, in run                                                                 
    self._target(*self._args, **self._kwargs)                                                                                 
  File "d:\soft\anaconda3\lib\subprocess.py", line 1366, in _readerthread                                                     
    buffer.append(fh.read())                                                                                                  
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 2827: illegal multibyte sequence                           
Traceback (most recent call last):                                                                                            
  File "d:\soft\anaconda3\lib\runpy.py", line 194, in _run_module_as_main                                                     
    return _run_code(code, main_globals, None,                                                                                
  File "d:\soft\anaconda3\lib\runpy.py", line 87, in _run_code                                                                
    exec(code, run_globals)                                                                                                   
  File "D:\soft\anaconda3\Scripts\objection.exe\__main__.py", line 7, in <module>                                             
  File "d:\soft\anaconda3\lib\site-packages\click\core.py", line 829, in __call__                                             
    return self.main(*args, **kwargs)                                                                                         
  File "d:\soft\anaconda3\lib\site-packages\click\core.py", line 782, in main                                                 
    rv = self.invoke(ctx)                                                                                                     
  File "d:\soft\anaconda3\lib\site-packages\click\core.py", line 1259, in invoke                                              
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                   
  File "d:\soft\anaconda3\lib\site-packages\click\core.py", line 1066, in invoke                                              
    return ctx.invoke(self.callback, **ctx.params)                                                                            
  File "d:\soft\anaconda3\lib\site-packages\click\core.py", line 610, in invoke                                               
    return callback(*args, **kwargs)                                                                                          
  File "d:\soft\anaconda3\lib\site-packages\objection\console\cli.py", line 371, in patchapk                                  
    patch_android_apk(**locals())                                                                                             
  File "d:\soft\anaconda3\lib\site-packages\objection\commands\mobile_packages.py", line 190, in patch_android_apk            
    patcher.inject_internet_permission()                                                                                      
  File "d:\soft\anaconda3\lib\site-packages\objection\utils\patchers\android.py", line 428, in inject_internet_permission     
    if internet_permission in self._get_appt_output():                                                                        
  File "d:\soft\anaconda3\lib\site-packages\objection\utils\patchers\android.py", line 306, in _get_appt_output               
    o = delegator.run(self.list2cmdline([                                                                                     
  File "d:\soft\anaconda3\lib\site-packages\delegator.py", line 320, in run                                                   
    c.block()                                                                                                                 
  File "d:\soft\anaconda3\lib\site-packages\delegator.py", line 238, in block                                                 
    stdout, stderr = self.subprocess.communicate()                                                                            
  File "d:\soft\anaconda3\lib\subprocess.py", line 1024, in communicate                                                       
    stdout, stderr = self._communicate(input, endtime, timeout)                                                               
  File "d:\soft\anaconda3\lib\subprocess.py", line 1416, in _communicate                                                      
    stdout = stdout[0]                                                                                                        
IndexError: list index out of range                                                                                           
Cleaning up temp files...                                                                                                     
```

**Comment by leonjza** [comment]
I am going to assume the app has some Chinese characters in the name. I am happy to accept a PR to improve this, I just don't have the available cycles at the moment to tackle this.

**Comment by leonjza** [comment]
Just remembered we have the `-z, --unzip-unicode` flag you can set for the patcher to help with this.

**Comment by muhawo** [comment]
https://github.com/sensepost/objection/issues/372#issuecomment-1536439903
试试这个
