### ISSUE TITLE
[bug] Fails to attach to process (iOS)

### ISSUE THREAD

**Issue by AnaCosteira** [sensepost/objection#459]
**Describe the bug**
Objection won't attach to any process, this is true regardless of which command is used regarding the gadgets (Says process refused to load frida-agent or terminated); 

**To Reproduce**
objection -d -g NAME explore
objection -d -g IDENTIFIER explore
objection -d -g PID explore

**Expected behavior**
Objection should hook to the application

**Evidence / Logs / Screenshots**

```
PS C:\Users\Test> objection -d -g 3553 explore
[debug] Agent path is: c:\users\test\appdata\local\programs\python\python37\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Apple iPhone`
[debug] Attempting to attach to process: `3553`
Traceback (most recent call last):
  File "C:\Users\Test\AppData\Local\Programs\Python\Python37\Scripts\objection-script.py", line 11, in <module>
    load_entry_point('objection==1.11.0', 'console_scripts', 'objection')()
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\objection\console\cli.py", line 114, in explore
    agent.inject()
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\objection\utils\agent.py", line 202, in inject
    session = self.get_session()
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\objection\utils\agent.py", line 152, in get_session
    self.session = self.device.attach(state_connection.gadget_name)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\users\test\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 156, in attach
    return Session(self._impl.attach(self._pid_of(target), *args, **kwargs))
frida.ProcessNotRespondingError: process with pid 3553 either refused to load frida-agent, or terminated during injection
```

**Environment :**
 - Device: iPhone 6S
 - OS: iOS 14.5 (jb w/ checkra1n)
 - Frida Version: 14.2.3, 14.2.9 and 14.2.17
- Objection Version 1.9.6 and 1.11.0

**Additional context**
Frida-PS -U works just fine, so it's possibly due to some incompatibility. Issue started after I updated iOS version and had to install the newest frida version.

**Comment by leonjza** [comment]
Does vanilla frida work for you?

**Comment by AnaCosteira** [comment]
Some stuff was working, but digging more into frida itself, this may be a frida issue. I'll move it to Frida's git.
