### ISSUE TITLE
[bug] Android frida.TransportError: timeout was reached

### ISSUE THREAD

**Issue by iamnasef** [sensepost/objection#464]
**Describe the bug**
Objection returns error everytime I try to connect. although frida works perfectly and returns all apps when I type frida-ps -Uai

**To Reproduce**
1. Run frida-ps -Uai to get package name
2. Run objection -d -g com.test explore 

**Expected behavior**
An objection terminal where I can write commands

**Evidence / Logs / Screenshots**

``` objection -d -g com.test explore
[debug] Agent path is: /usr/local/lib/python3.8/dist-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `Redmi Note 7`
[debug] Attempting to attach to process: `com.test`
[debug] Process attached!
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/usr/local/lib/python3.8/dist-packages/objection/utils/agent.py", line 203, in inject
    self.script = session.create_script(source=self._get_agent_source())
  File "/usr/local/lib/python3.8/dist-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/frida/core.py", line 204, in create_script
    return Script(self._impl.create_script(*args, **kwargs))
frida.TransportError: timeout was reached

```

**Environment (please complete the following information):**
 - Device: Xiaomi Note7
 - OS: Android 10
 - Frida Version 14.2.17
- Objection Version 1.11.0

**Application**
I've tried multiple applications all with the same result

**Comment by iamnasef** [comment]
Unlike iOS, you have to open the application first then attach objection to the application.

**Comment by iamnasef** [comment]
I tried to run the same command with the application in the foreground and background and still the same result.

**Comment by lf-** [comment]
I don't know what's going on here, but I can tell you that you're not alone: I'm also having this.

**Comment by lf-** [comment]
Possibly related logcat with these packages:

```
» pip list
Package        Version
-------------- ---------
certifi        2021.5.30
chardet        4.0.0
cli-helpers    2.1.0
click          8.0.1
colorama       0.4.4
configobj      5.0.6
delegator.py   0.1.1
Flask          2.0.1
frida          14.2.18
frida-tools    9.2.5
idna           2.10
itsdangerous   2.0.1
Jinja2         3.0.1
litecli        1.6.0
MarkupSafe     2.0.1
objection      1.11.0
pexpect        4.8.0
pip            21.1.1
prompt-toolkit 3.0.19
ptyprocess     0.7.0
Pygments       2.9.0
requests       2.25.1
semver         2.13.0
setuptools     56.0.0
six            1.16.0
sqlparse       0.4.1
tabulate       0.8.9
terminaltables 3.1.0
urllib3        1.26.5
wcwidth        0.2.5
Werkzeug       2.0.1
``` 

```
06-20 00:48:17.208 18464 18464 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.creative.apps.superxfiplayer-bDblWs9grkvc0cGLtp0jYA==/base.apk"],nativeLibraryDirectories=[/data/app/com.creative.apps.superxfiplayer-bDblWs9grkvc0cGLtp0jYA==/lib/arm64, /data/app/com.creative.apps.superxfiplayer-bDblWs9grkvc0cGLtp0jYA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libfrida-gadget.so"
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1667)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at com.creative.apps.superxfiplayer.activities.MainActivity.<clinit>(Unknown Source:2)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.support.v4.app.CoreComponentFactory.instantiateActivity(Unknown Source:0)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1269)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3287)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3514)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
06-20 00:48:17.208 18464 18464 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
06-20 00:48:17.208 18464 18464 I Process : Sending signal. PID: 18464 SIG: 9
```

**Comment by kanadeblisst** [comment]
I don't know what's going on here, but I can tell you that you're not alone: I'm also having this. It's strange that it's normal to use it on windows, and Frida (14.2.18) in windows and Kali is the same as the version of object (1.11.0)

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen. Could perhaps have been because frida-server was not running, frida-ps might still work without it but you won't be able to attach to or spawn applications.

**Comment by wbznan4** [comment]
Replacing the process name with the process id in the objection command worked for me, might be worth a try.
