### ISSUE TITLE
[bug?] Am I a noob or what ?

### ISSUE THREAD

**Issue by maximebories** [sensepost/objection#480]
**Describe the bug**
I have been successfully using Frida for a few month, but I never had had the chance to have Objection working. Up until recently it was because of a supposed openssl version not supported by libmobileidevice. That was on a MacBook Pro. Right now on Mac mini this is what I'm experiencing:

![Screenshot 2021-09-06 at 17 47 52](https://user-images.githubusercontent.com/30550722/132253894-240f7b7e-94cf-4eea-bec8-2d3ba3584bec.png)

**To Reproduce**
1. pip install frida-tools
2. pip install objection
3. objection --debug --gadget frida-server  explore

**Similar issues**
Only one I found with same exact [error output](https://github.com/sensepost/objection/issues/197)

**Environment**
 - Device: iPhone 7 (Global 9,3)
 - iOS 14.7.1
 - macOS 11.5.2
 - Frida 15.0.18
 - Frida-server 15.1.1
- Objection 1.11.0

**Comment by leonjza** [comment]
Please run it again with the `--debug` flag and paste the output?

**Comment by maximebories** [comment]
Thank you for your response. I did tried that and there was no difference at all, sorry for not mentioning it. It's not surprising thought, Objection doesn't pass the debug flag and Frida is the first call in the error stack. I will try to force the debug option on the Frida side.

**Comment by leonjza** [comment]
The debug flag should enable the source map so that we can see where in the agent the crash occurred. Please paste the crash with the flag enabled.

**Comment by maximebories** [comment]
Exact, I need to put more contrast. Here you go:

![Screenshot 2021-09-07 at 21 19 11](https://user-images.githubusercontent.com/30550722/132399260-24a7abf8-238d-40f0-91a1-7c72f47c569a.png)

**Comment by leonjza** [comment]
No it's not the same. It now tells us line 8 in `environment.ts` is to blame, but sadly it seems like the sourcemap is wrong.

**Comment by novitae** [comment]
Any update on this ? I am getting the same issue
```
ae@MBP-de-t frida % objection --debug --gadget IMRemoteURLConnectionAgent explore
[debug] Agent path is: /usr/local/lib/python3.9/site-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `iPhone`
[debug] Attempting to attach to process: `IMRemoteURLConnectionAgent`
[debug] Process attached!
Agent injected and responds ok!
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/objection/console/cli.py", line 156, in explore
    device_info = get_device_info()
  File "/usr/local/lib/python3.9/site-packages/objection/commands/device.py", line 27, in get_device_info
    package_info = api.env_ios()
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 400, in _rpc_request
    raise result[2]
frida.core.RPCException: TypeError: cannot read property 'currentDevice' of undefined
    at <anonymous> (src/generic/environment.ts:55)
    at envIos (src/rpc/environment.ts:8)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
```
### env
- iPhone 6 iOS 12.5.5 jailbroken with checkra1n
- macOS X 12.3
- frida server 15.1.22
- frida on macOS 15.1.22

my Frida is completely fine, it is the first time I am using objection (and the process I am targeting is running while using the script, same error targeting via pid)

**Comment by novitae** [comment]
> I just realised that ya'll targeting processes that are not mobile processes. Objection only supports mobile apps at this point in time. If someone is keen, the reason it fails is because [these](https://github.com/sensepost/objection/blob/master/agent/src/generic/environment.ts#L67) calls on `UIDevice` won't work on all processes. We could probably rip out the device specific calls and make objection work on any process.

You should rename the issue with the exception we get, so people having the same issue are seing that.

**Comment by RobLinux** [comment]
Any update with this ?
