### ISSUE TITLE
Unable to determine URL to download the library[bug] Bug Description Here

### ISSUE THREAD

**Issue by paulalan2901** [sensepost/objection#499]
Don't know why I am getting this error whenever I tried to run the objection command to patch an application. The tool was working a few minutes beforehand. Just wanted to bring this to attention!

I am running Objection on Windows 10 OS.

```
C:\Users\user\AndroidStudioProjects\testapp\APKFolder>objection patchapk --source mush_pulled.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: x86
Using latest Github gadget version: 15.1.10
Remote FridaGadget version is v15.1.10, local is v15.1.9. Downloading...
Unable to determine URL to download the library
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\Scripts\objection-script.py", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\objection\console\cli.py", line 373, in patchapk
    patch_android_apk(**locals())
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\objection\commands\mobile_packages.py", line 171, in patch_android_apk
    android_gadget.download() \
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\objection\utils\patchers\android.py", line 114, in download
    download_url = self._get_download_url()
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\objection\utils\patchers\android.py", line 150, in _get_download_url
    raise Exception('Unable to determine URL for Android gadget download.')
Exception: Unable to determine URL for Android gadget download.
```
Tried reinstalling objection but it still does not work. It shows the same error.

**Comment by leonjza** [comment]
As you logged this, Frida 15.1.10 got released. The build artefacts take some time to upload to Github which is why this failed. It noticed the new version, but the gadget's weren't available yet.

Just try again.

Leaving this open to enhance this to fall back to a previous version should this happen again.
