### ISSUE TITLE
[bug] Bug Description Here

### ISSUE THREAD

**Issue by Joytracy** [sensepost/objection#518]
root# objection -N -h 192.168.0.101 -p 8888 -g com.android.settings explore
Using networked device @`192.168.0.101:8888`
Agent injected and responds ok!

     _   _         _   _
 ___| |_|_|___ ___| |_|_|___ ___
| . | . | | -_|  _|  _| | . |   |
|___|___| |___|___|_| |_|___|_|_|
      |___|(object)inject(ion) v1.11.0

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.android.settings on (google: 11) [net] # frida
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'filename'

Python stack trace: Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/objection/commands/frida_commands.py", line 38, in frida_environment
    ('Script Filename', frida_env['filename']),
KeyError: 'filename'

com.android.settings on (google: 11) [net] #

**Comment by Joytracy** [comment]
I don't think I described it well
