### ISSUE TITLE
启动objection时候,我打印frida的基本信息报错，但是打印env没有报错

### ISSUE THREAD

**Issue by 193030146** [sensepost/objection#535]
com.android.settings on (Android: 8.0.0) [usb] # frida
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'filename'

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.9/dist-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.9/dist-packages/objection/commands/frida_commands.py", line 38, in frida_environment
    ('Script Filename', frida_env['filename']),
KeyError: 'filename'

**Comment by CDuPlooy** [comment]
How did you install objection?

**Comment by saucer-man** [comment]
me too，I alse meet this problem，and I install objection by`pip3 install objection`

**Comment by Irhtn** [comment]
frida版本过高，我之前用的python 3.10和frida15.1.17,切换到了python 3.7,frida=14.2.18后可以正运行

**Comment by leonjza** [comment]
Apologies, I spotted the bug now! Thanks!

**Comment by leonjza** [comment]
Actually, I'm confused by this one. We're referencing the key [here](https://github.com/sensepost/objection/blob/1.11.0/objection/commands/frida_commands.py#L38), and even if it were null, it's populated [here](https://github.com/sensepost/objection/blob/1.11.0/agent/src/generic/environment.ts#L32). Will debug.
