### ISSUE TITLE
frida.InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by PeterJoins** [sensepost/objection#549]
$ objection -g  com.xxx  explore
Using USB device `Pixel 2 XL`
Agent injected and responds ok!
Traceback (most recent call last):
  File "/home/w/.local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/w/.local/lib/python3.6/site-packages/objection/console/cli.py", line 156, in explore
    device_info = get_device_info()
  File "/home/w/.local/lib/python3.6/site-packages/objection/commands/device.py", line 22, in get_device_info
    environment = api.env_runtime()
  File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 468, in method
    return script._rpc_request('call', js_name, args, **kwargs)
  File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 400, in _rpc_request
    raise result[2]
frida.InvalidOperationError: script has been destroyed
Asking jobs to stop...
Unloading objection agent...
Unable to run cleanups: script is destroyed

I want to use spawn method to attach a process to report an error, how to solve it?

**Comment by leonjza** [comment]
Sorry, but it is impossible to know what causes the error without more information. Filling in the bug report template will be one way to help.

The only thing I can tell you from the stack trace is that it looks like it fails in the device runtime enumeration code.

**Comment by PeterJoins** [comment]
> Sorry, but it is impossible to know what causes the error without more information. Filling in the bug report template will be one way to help.
> 
> The only thing I can tell you from the stack trace is that it looks like it fails in the device runtime enumeration code.

This is the case for every process. It is normal to attach by pid.

**Comment by leonjza** [comment]
Can try using just vanilla Frida to see if that helps? Sorry, without more details/logs/debug output etc there really isn't much more I can do to help.

**Comment by PeterJoins** [comment]
> Can try using just vanilla Frida to see if that helps? Sorry, without more details/logs/debug output etc there really isn't much more I can do to help.

ok ,still thank you.

**Comment by jaisurya11** [comment]
> $ objection -g com.xxx explore Using USB device `Pixel 2 XL` Agent injected and responds ok! Traceback (most recent call last): File "/home/w/.local/bin/objection", line 11, in sys.exit(cli()) File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 829, in **call** return self.main(*args, **kwargs) File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/w/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/w/.local/lib/python3.6/site-packages/objection/console/cli.py", line 156, in explore device_info = get_device_info() File "/home/w/.local/lib/python3.6/site-packages/objection/commands/device.py", line 22, in get_device_info environment = api.env_runtime() File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 468, in method return script._rpc_request('call', js_name, args, **kwargs) File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 26, in wrapper return f(*args, **kwargs) File "/home/w/.local/lib/python3.6/site-packages/frida/core.py", line 400, in _rpc_request raise result[2] frida.InvalidOperationError: script has been destroyed Asking jobs to stop... Unloading objection agent... Unable to run cleanups: script is destroyed
> 
> I want to use spawn method to attach a process to report an error, how to solve it?

Have you find how to resolve this error?

**Comment by sudosuraj** [comment]
Instead of:
```
> objection -g com.myapp.mobile explore
```


Just do:
```
 > frida-ps -Uai
 PID  Name          Identifier
----  ------------  ---------------------------
1337  MyApp      com.myapp.mobile
```

```
> objection -g 1337 explore
```
