### ISSUE TITLE
Code signing failed

### ISSUE THREAD

**Issue by pich4ya** [sensepost/objection#55]
MacOS 10.13.3

IPA = DVIA.ipa
http://damnvulnerableiosapp.com/?paiddownloads_id=11

$ pip3.6 show objection
Name: objection
Version: 1.2.4

$ npm list -g --depth=0
/usr/local/lib
├── applesign@2.2.0
[...]

```
$ objection patchipa -s "/Users/XXX/DVIA.ipa" -c XXXYYYZZZ
objc[92749]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[92749]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Using latest Github gadget version: 10.6.53
Patcher will be using Gadget version: 10.6.53
No provision file specified, searching for one...
Found provision file /Users/XXX/Library/Developer/Xcode/DerivedData/YYYY1-elizruhxoinlpjarbzfeauucavdp/Build/Products/Debug-iphoneos/YYYY1.app/embedded.mobileprovision expiring in 6 days, 12:02:41.160930
Found provision file /Users/XXX/Library/Developer/Xcode/DerivedData/YYYY2-axmclaoqvldmvpfandfjkjhkasbl/Build/Products/Debug-iphoneos/YYYY2.app/embedded.mobileprovision expiring in 6 days, 12:10:26.160930
Found a valid provisioning profile
Working with app: DamnVulnerableIOSApp.app
Bundle identifier is: com.highaltitudehacks.dvia
Creating Frameworks directory for FridaGadget...
Codesigning 1 .dylib's with signature XXXYYYZZZ
Code signing: FridaGadget.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Cannot find entitlements in binary. Using defaults
/var/folders/50/7j5rhs4n4tq9hw9mjm2yntg40000gn/T/DVIA-frida.ipa.43fc6a5a-6013-4f9f-b3cb-909c6450fe23/Payload/DamnVulnerableIOSApp.app 120x120.png [TypeError: Buffer.alloc is not a function]
TypeError: Buffer.alloc is not a function
Cannot find any MACH0 binary to sign
Cannot find any MACH0 binary to sign undefined
[TypeError: Buffer.alloc is not a function] undefined

Copying final ipa from /var/folders/50/7j5rhs4n4tq9hw9mjm2yntg40000gn/T/DVIA-frida-codesigned.ipa to current directory...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 195, in patchipa
    patch_ios_ipa(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 75, in patch_ios_ipa
    os.path.join(os.path.abspath('.'), os.path.basename(patcher.get_patched_ipa_path())))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/50/7j5rhs4n4tq9hw9mjm2yntg40000gn/T/DVIA-frida-codesigned.ipa'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/50/7j5rhs4n4tq9hw9mjm2yntg40000gn/T/DVIA-frida-codesigned.ipa'
```

I have tried with multiple apps, still got the similar errors during the signing process. I pulled the unencrypted IPAs using Clutch2. Are there any further requirement on input IPA?

**Comment by leonjza** [comment]
> TypeError: Buffer.alloc is not a function

Interesting. I see this error relates to a few Node related issues. Can we try and see what happens when you manually `applesign` the patched IPA? To do this, run the following:

- `objection patchipa -s source.ipa -c XXYY --skip-cleanup`. This tells the patcher to not try and delete any artefacts generated during the patching process.
- Take note of the temp path where the zipped up, patched IPA lives.
- Run [`applesign`](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/ios.py#L396) on that target, patched IPA with: `applesign -i YOUR_CODE_SIG -m PROVISION_FILE_LOCATION -o OUTPUT`.

Let me know if there is any interesting output!

**Comment by leonjza** [comment]
Ooh just saw the edit stating that this is DVIA. Will test locally.

**Comment by leonjza** [comment]
Seems to work ok. Note that this app does not need to be run through clutch as it does not have Apples Fairplay DRM applied.

```
~/scratch » objection patchipa -c XXYY -s DamnVulnerableiOSApp.ipa
Using latest Github gadget version: 10.6.53
Remote FridaGadget version is v10.6.53, local is v10.6.52. Downloading...
Downloading from: https://github.com/frida/frida/releases/download/10.6.53/frida-gadget-10.6.53-ios-universal.dylib.xz
Downloading iOS dylib to /Users/xxx/.objection/ios/FridaGadget.dylib.xz...
Unpacking /Users/xxx/.objection/ios/FridaGadget.dylib.xz...
Cleaning up downloaded archives...
Patcher will be using Gadget version: 10.6.53
No provision file specified, searching for one...
Found provision file /Users/xxx/Library/Developer/Xcode/DerivedData/xxxxBuild/Products/Debug-iphoneos/xxx.app/embedded.mobileprovision expiring in 4 days, 13:42:49.072759
Found a valid provisioning profile
Working with app: DamnVulnerableIOSApp.app
Bundle identifier is: com.highaltitudehacks.dvia
Creating Frameworks directory for FridaGadget...
Codesigning 1 .dylib's with signature XXYY
Code signing: FridaGadget.dylib
Creating new archive with patched contents...
Codesigning patched IPA...
Cannot find entitlements in binary. Using defaults

Copying final ipa from /var/folders/nn/7rzmzs_920n8qvff8n9nf1rm0000gn/T/DamnVulnerableiOSApp-frida-codesigned.ipa to current directory...
Cleaning up temp files...
(venv3) ------------------------------------------------------------
~/scratch » ls *.ipa
DamnVulnerableiOSApp-frida-codesigned.ipa DamnVulnerableiOSApp.ipa
```

**Comment by pich4ya** [comment]
No. I didn't use Clutch. I think it is problem with something relates to Node? 

$ node --version
v5.8.0

**Comment by pich4ya** [comment]
Okay... I upgraded Node. And everything worked !! haha

**Comment by leonjza** [comment]
Awesome. 👍
