### ISSUE TITLE
[bug] exception when loading script

### ISSUE THREAD

**Issue by g2asell2019** [sensepost/objection#553]
**Describe the bug**
when I run objection with _--startup-script_, objection just exit the REPL due to resume command

**To Reproduce**
1.  objection --gadget "<redacted>" explore --startup-script "main_v3.1.4_clean.js"
2.  REPL crash

**Expected behavior**
Expect REPL not crash

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text

F:\<redacted>objection --debug --gadget "<redacted>" explore --startup-script "main_v3.1.4_clean.js"
[debug] Agent path is: c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Minh’s iPad`
[debug] Attempting to attach to process: `<redacted>`
[debug] Unable to find process: `<redacted>`, attempting spawn
[debug] PID `20078` spawned, attaching...
[debug] Resuming PID `20078`
Agent injected and responds ok!
Importing and running startup script at: <_io.TextIOWrapper name='main_v3.1.4_clean.js' mode='r' encoding='cp1252'>
[*] Patching...
[*] Patching...
[*] nop call suspend
[*] Patching...
[*] Patching...
[*] Patching...
[*] Patching...
[*] Patching...
[debug] Resuming PID `20078`
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python37\Scripts\objection-script.py", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\objection\console\cli.py", line 149, in explore
    response = agent.single(startup_script.read())
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\objection\utils\agent.py", line 249, in single
    self.device.resume(self.spawned_pid)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python37\lib\site-packages\frida\core.py", line 148, in resume
    self._impl.resume(self._pid_of(target))
frida.InvalidOperationError: process is not suspended
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
```

**Environment (please complete the following information):**
 - Device: iPad Pro 2nd gen
 - OS: 12.0.1
 - Frida Version 14.2.13
- Objection Version 1.11.0

**Application**
I tested with my private app, probably you reproduce with others app

**Additional context**
I think it's probably resume command cause the crash of REPL
When objection is load without startup-script it's just fine, when load with startup-script it's just automatically add --no-pause but in objection it sends resume action then REPL crash

**Comment by IPMegladon** [comment]
This logic has been refactored at some point an may have resolved this issue.
Closing issue as stale for now, feel free to reopen.
