### ISSUE TITLE
[bug] Press Any Key To Continue as Version Number on Windows

### ISSUE THREAD

**Issue by Meerkov** [sensepost/objection#566]
**Describe the bug**
```
objection patchapk -s agsabase.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: x86
Using latest Github gadget version: 15.2.2
Patcher will be using Gadget version: 15.2.2
Detected apktool version as: Press any key to continue . . .
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\Scripts\objection-script.py", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\objection\console\cli.py", line 373, in patchapk
    patch_android_apk(**locals())
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\objection\commands\mobile_packages.py", line 185, in patch_android_apk
    if not patcher.is_apktool_ready():
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\objection\utils\patchers\android.py", line 245, in is_apktool_ready
    if semver.compare(o, min_version) < 0:
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\semver.py", line 159, in wrapper
    return func(*args, **kwargs)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\semver.py", line 856, in compare
    v1 = VersionInfo.parse(ver1)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\site-packages\semver.py", line 726, in parse
    raise ValueError("%s is not valid SemVer string" % version)
ValueError: Press any key to continue . . . is not valid SemVer string
Cleaning up temp files...
```

**To Reproduce**

I see that this has a bugfix in the codebase already, but I still run into the same issue.

**Similar issues**
(https://github.com/sensepost/objection/blob/e89e455198eb5cb4e019239c4bddfcd194d45337/objection/utils/patchers/android.py#L235)

**Comment by leonjza** [comment]
Unfortunately you didn't fill in the issue template to help fast track this, so I have to ask. Sure you got the latest version of objection running?

**Comment by Meerkov** [comment]
Yup, Objectionversion 1.11.0

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
