### ISSUE TITLE
patchapk - error in patch

### ISSUE THREAD

**Issue by yehgdotnet** [sensepost/objection#58]
In patching one apk file, the following error trigger:

Test APK download link: https://mega.nz/#!s4JCWaQa!KrqDqb44K_54qqWiD2_JwMSTTJAeDrHLMUT7xi8cJtU

```
objection patchapk -s l.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using latest Github gadget version: 10.6.54
Patcher will be using Gadget version: 10.6.54
Unpacking l.apk
An error may have occured while extracting the APK.
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at java.base/java.nio.ByteBuffer.wrap(ByteBuffer.java:388)
	at brut.androlib.res.decoder.StringBlock.decodeString(StringBlock.java:297)
	at brut.androlib.res.decoder.StringBlock.getString(StringBlock.java:110)
	at brut.androlib.res.decoder.StringBlock.getHTML(StringBlock.java:126)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:341)
	at brut.androlib.res.decoder.ARSCDecoder.readEntryData(ARSCDecoder.java:257)
	at brut.androlib.res.decoder.ARSCDecoder.readTableType(ARSCDecoder.java:233)
	at brut.androlib.res.decoder.ARSCDecoder.readTableTypeSpec(ARSCDecoder.java:156)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:118)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:80)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:599)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:163)
	at brut.apktool.Main.main(Main.java:72)

App already has android.permission.INTERNET
Smali not found in smali directory. This might be a multidex APK. Searching...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 219, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 155, in patch_android_apk
    patcher.inject_load_library()
  File "/usr/local/lib/python3.6/site-packages/objection/utils/patchers/android.py", line 496, in inject_load_library
    raise Exception('Unable to find smali to patch!')
Exception: Unable to find smali to patch!
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/dy/vrzdl9g97r383jmfvrq43fvr0000gn/T/tmpndaytecv.apktemp.objection.apk'
```

**Comment by leonjza** [comment]
When it breaks in this phase of the patching process it typically means `apktool` did not succeed. Could you check if you can get `apktool` to be happy with this APK? As soon as I have some time I will test too with the link you provided. Thanks! 🙏

**Comment by yehgdotnet** [comment]
You mean, trying with multiple versions of apktool?

Or does it happen due to the target app using complicated library?

**Comment by leonjza** [comment]
This is a target app <> apktool thing yeah. I have not tested yet, but it might be worth it to check out #56 with `-r` and apktool. A quick manual edit might help too until I can test and release an update.

**Comment by burrowingsec** [comment]
@yehgdotnet  Just tested the ` l.apk ` app both with the ` -r` flag and without. I can confirm that adding the flag to your copy of Objection will fix your error and allow you to patch successfully.

You will want to uninstall the version of Objection you have now through ` pip3 uninstall objection `. That will work even if you installed via the source code from Github. You'll then want to clone this repository and edit the ` objection/objection/utils/patchers/android.py ` file. Find the ` unpack_apk ` function; it looks like the below:

```
def unpack_apk(self):
        """
            Unpack an APK with apktool.

            :return:
        """

        click.secho('Unpacking {0}'.format(self.apk_source), dim=True)

        o = delegator.run(list2cmdline([
            self.required_commands['apktool']['location'],
            'decode',
            '-f',
            '-o',
            self.apk_temp_directory,
            self.apk_source
        ]), timeout=self.command_run_timeout)
```

You'll want to edit that section of code to look like the below (the only modification is the addition of the line with ` -r `):

```
def unpack_apk(self):
        """
            Unpack an APK with apktool.

            :return:
        """

        click.secho('Unpacking {0}'.format(self.apk_source), dim=True)

        o = delegator.run(list2cmdline([
            self.required_commands['apktool']['location'],
            'decode',
            '-f',
            '-r',
            '-o',
            self.apk_temp_directory,
            self.apk_source
        ]), timeout=self.command_run_timeout)
```

Just to confirm everything went well with patching:

```
bjection patchapk -s Desktop/l.apk --gadget-version 10.6.33 --architecture armeabi-v7a
Using manually specified version: 10.6.33
Patcher will be using Gadget version: 10.6.33
Unpacking Desktop/l.apk
App already has android.permission.INTERNET
Smali not found in smali directory. This might be a multidex APK. Searching...
Found smali at: /tmp/tmp00ittekg.apktemp/smali_classes2/com/lazada/activities/EnterActivity.smali
Reading smali from: /tmp/tmp00ittekg.apktemp/smali_classes2/com/lazada/activities/EnterActivity.smali
Injecting loadLibrary call at line: 13
Writing patched smali back to: /tmp/tmp00ittekg.apktemp/smali_classes2/com/lazada/activities/EnterActivity.smali
Creating library path: /tmp/tmp00ittekg.apktemp/lib/armeabi-v7a
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
jar signed.

Signed the new APK
Performing zipalign
Zipaling completed
Copying final apk from /tmp/tmp00ittekg.apktemp.aligned.objection.apk to current directory...
Cleaning up temp files...
```

**Comment by yehgdotnet** [comment]
@burrowingsec 
@leonjza 

Great thanks. Your solution -r works!

**Comment by leonjza** [comment]
Thanks for the feedback @yehgdotnet ! I should get some time next week to write some patches to add this (with a flag too).

**Comment by leonjza** [comment]
I have released v1.2.5, which should hopefully solve this. If there are cases where you might need resources to be decoded, add the new `--decode-resources` flag.

`pip3 install objection --upgrade`, test and let me know how it goes!

**Comment by MaianaBt** [comment]
Please, inform where put the tag `--decode-resources`? I'm trying to execute this command `objection patchapk -s test_app.apk` but occurred the same error.

**Comment by Mohit0** [comment]
I tried the above scenario and the above solution doesn't work for me.
Application URL: http://tiny.cc/r13upz

`App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...
Smali not found in smali directory. This might be a multidex APK. Searching...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/objection/console/cli.py", line 371, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.8/dist-packages/objection/commands/mobile_packages.py", line 200, in patch_android_apk
    patcher.inject_load_library(target_class=target_class)
  File "/usr/local/lib/python3.8/dist-packages/objection/utils/patchers/android.py", line 781, in inject_load_library
    activity_path = self._determine_smali_path_for_class(
  File "/usr/local/lib/python3.8/dist-packages/objection/utils/patchers/android.py", line 607, in _determine_smali_path_for_class
    raise Exception('Unable to find smali to patch!')
Exception: Unable to find smali to patch!
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpg7vc40_e.apktemp.objection.apk'
`

Any suggestion how to fix the issue?

**Comment by leonjza** [comment]
The hint is here: 

> Exception: Unable to find smali to patch!

Try and specify a target class for the gadget (see `--help` on the `patchapk` command).

**Comment by Mohit0** [comment]
I already tried that but still no luck.
