### ISSUE TITLE
frida.TimedOutError: unexpectedly timed out while initializing suspended process

### ISSUE THREAD

**Issue by senolatac** [sensepost/objection#585]
**Describe the bug**
Timeout occurred on objection explore

**To Reproduce**
1. Run command `objection --gadget "com.apple.AppStore" explore`

**Evidence / Logs / Screenshots**

```
Using USB device `iPhone`
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/usr/local/lib/python3.9/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/usr/local/lib/python3.9/site-packages/objection/utils/agent.py", line 169, in get_session
    self.session = self.device.attach(self.spawned_pid)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/frida/core.py", line 800, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
frida.TimedOutError: unexpectedly timed out while initializing suspended process
```
**Environment (please complete the following information):**
 - Device: İPhone 7 
 - OS: 15.3.1
 - Frida Version: 16.0.2
- Objection Version: 1.11.0

**Comment by IPMegladon** [comment]
Stale issue, feel free to reopen.
