### ISSUE TITLE
[patchapk] rebuiding apk - error | Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error:

### ISSUE THREAD

**Issue by yehgdotnet** [sensepost/objection#59]
Hello awesome SensePost team, 

I faced error in another APK file in rebuilding phase. 

Problem APK:  https://mega.nz/#!h8wiyIAR!V5okSQdKu1KkCTUGQKzxlIE706LychmkrDqXTcIXm_8

```
$ objection patchapk -s /temp/r.apk
objc[63892]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[63892]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
No architecture specified. Determining it using `adb`...
Detected target device architecture as: armeabi-v7a
Using Gadget version: 10.6.55
Unpacking /temp/r.apk
App already has android.permission.INTERNET
Reading smali from: /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/smali/com/redmart/redmart/usecases/start/StartActivity.smali
Injecting into an existing constructor
Injecting loadLibrary call at line: 40
Writing patched smali back to: /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/smali/com/redmart/redmart/usecases/start/StartActivity.smali
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error:

W: /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/res/values-v24/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.OptionsPanel'.
W:
W: /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/res/values-v24/styles.xml:8: error: Error retrieving parent for item: No resource found that matches the given name '@android:style/Animation.LockScreen'.
W:
Exception in thread "main" brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/brut_util_Jar_1783797410346703816.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 198, --version-name, 2.5.37.3463, --no-version-vectors, -F, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/APKTOOL4684494251419083774.tmp, -0, arsc, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/res, -M, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/AndroidManifest.xml]
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:492)
	at brut.androlib.Androlib.buildResources(Androlib.java:426)
	at brut.androlib.Androlib.build(Androlib.java:305)
	at brut.androlib.Androlib.build(Androlib.java:270)
	at brut.apktool.Main.cmdBuild(Main.java:227)
	at brut.apktool.Main.main(Main.java:75)
Caused by: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/brut_util_Jar_1783797410346703816.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 198, --version-name, 2.5.37.3463, --no-version-vectors, -F, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/APKTOOL4684494251419083774.tmp, -0, arsc, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/res, -M, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/AndroidManifest.xml]
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:456)
	at brut.androlib.Androlib.buildResourcesFull(Androlib.java:478)
	... 5 more
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/brut_util_Jar_1783797410346703816.tmp, p, --forced-package-id, 127, --min-sdk-version, 15, --target-sdk-version, 22, --version-code, 198, --version-name, 2.5.37.3463, --no-version-vectors, -F, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/APKTOOL4684494251419083774.tmp, -0, arsc, -0, META-INF/services/com.fasterxml.jackson.core.JsonFactory, -0, META-INF/services/com.fasterxml.jackson.core.ObjectCodec, -0, arsc, -I, /Users/user/Library/apktool/framework/1.apk, -S, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/res, -M, /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp/AndroidManifest.xml]
	at brut.util.OS.exec(OS.java:95)
	at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:450)
	... 6 more

Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
jarsigner: unable to open jar file: /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp.objection.apk

Signed the new APK
Performing zipalign
Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error:

Unable to open '/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp.objection.apk' as zip archive

Zipaling completed
Copying final apk from /var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp.aligned.objection.apk to current directory...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/objection/console/cli.py", line 213, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 156, in patch_android_apk
    shutil.copyfile(patcher.get_patched_apk_path(), os.path.join(os.path.abspath('.'), destination))
  File "/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp.aligned.objection.apk'
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/var/folders/4p/6jcgwmts2dl5j6zjc2zj0scm0000gn/T/tmpn3o7sld1.apktemp.objection.apk'
```

**Comment by leonjza** [comment]
Looks like apktool again. The actual rebuild happens [here](https://github.com/sensepost/objection/blob/master/objection/utils/patchers/android.py#L592-L598) if you wanted to play with some flags. This is still on my hit list for next week though.

**Comment by leonjza** [comment]
I have released v1.2.5, which should hopefully solve this. If there are cases where you might need resources to be decoded, add the new `--decode-resources` flag.

`pip3 install objection --upgrade`, test and let me know how it goes!

**Comment by leonjza** [comment]
@romariolopezc Unfortunately these cases usually mean you will have to manually fix up resources and or other things that APK tool might be having trouble with. Try manually decoding and then rebuilding the target APK with apktool and see what you need to do to get it to build fine. Once you have that sorted, use the `--pause` flag with the objection patcher, apply the fixes you found and continue when done.

HTH

**Comment by romariolopezc** [comment]
I fixed it with `--skip-resources`, thanks @leonjza

**Comment by musashi42** [comment]
thanks @leonjza and @romariolopezc   , worked for me as well

**Comment by dgrivera** [comment]
hi please can anyone explain how to use --skip-resources?

**Comment by musashi42** [comment]
I use it like this:
$ objection patchapk --source base.apk --skip-resources

**Comment by dgrivera** [comment]
on zipalign it said:


Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error: 

/usr/bin/zipalign: error while loading shared libraries: liblog.so.0: cannot open shared object file: No such file or directory

Zipaling completed
Copying final apk from /tmp/tmpr2zhmo0z.apktemp.aligned.objection.apk to Update_HomeCredit_App.objection.apk in current directory...
Traceback (most recent call last):
  File "/root/virtual-python3/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/virtual-python3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/console/cli.py", line 244, in patchapk
    patch_android_apk(**locals())
  File "/root/virtual-python3/lib/python3.6/site-packages/objection/commands/mobile_packages.py", line 182, in patch_android_apk
    shutil.copyfile(patcher.get_patched_apk_path(), os.path.join(os.path.abspath('.'), destination))
  File "/root/virtual-python3/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpr2zhmo0z.apktemp.aligned.objection.apk'
Cleaning up temp files...
