### ISSUE TITLE
TypeError: cannot read property 'overloads' of undefined

### ISSUE THREAD

**Issue by flamecopper** [sensepost/objection#608]
A Frida agent exception has occurred.
TypeError: cannot read property 'overloads' of undefined
    at <anonymous> (/script1.js:18754)
    at forEach (native)
    at <anonymous> (/script1.js:18769)
    at <anonymous> (/script1.js:19157)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at perform (frida/node_modules/frida-java-bridge/index.js:205)
    at <anonymous> (/script1.js:19162)
    at Promise (native)
    at wrapJavaPerform (/script1.js:19163)
    at <anonymous> (/script1.js:18772)
    at androidHookingWatchClass (/script1.js:22613)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)

This happens when I was trying to watch for the activities.

android hooking watch class com.xxx.MainActivity

**Comment by ray-yuruisoft** [comment]
same problem! it seems like there are some overide motherd exist

**Comment by sangcx5** [comment]
same problem! is there any solution? :D

**Comment by IPMegladon** [comment]
Please run objection with the debug flag `-d` and provide the error output from that.

**Comment by Anas35** [comment]
```
A Frida agent exception has occurred.
TypeError: cannot read property 'overloads' of undefined
    at <anonymous> (src/android/hooking.ts:92)
    at forEach (native)
    at <anonymous> (src/android/hooking.ts:113)
    at <anonymous> (src/android/lib/libjava.ts:9)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at perform (frida/node_modules/frida-java-bridge/index.js:203)
    at <anonymous> (src/android/lib/libjava.ts:13)
    at Promise (native)
    at wrapJavaPerform (src/android/lib/libjava.ts:14)
    at <anonymous> (src/android/hooking.ts:117)
    at androidHookingWatchClass (src/rpc/android.ts:47)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)
```

```
Python stack trace: Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\commands\android\hooking.py", line 137, in watch_class
    api.android_hooking_watch_class(class_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\x\AppData\Local\Programs\Python\Python310\lib\site-packages\frida\core.py", line 497, in _rpc_request
    raise result.error
frida.core.RPCException: TypeError: cannot read property 'overloads' of undefined
    at <anonymous> (src/android/hooking.ts:92)
    at forEach (native)
    at <anonymous> (src/android/hooking.ts:113)
    at <anonymous> (src/android/lib/libjava.ts:9)
    at <anonymous> (frida/node_modules/frida-java-bridge/lib/vm.js:12)
    at perform (frida/node_modules/frida-java-bridge/index.js:203)
    at <anonymous> (src/android/lib/libjava.ts:13)
    at Promise (native)
    at wrapJavaPerform (src/android/lib/libjava.ts:14)
    at <anonymous> (src/android/hooking.ts:117)
    at androidHookingWatchClass (src/rpc/android.ts:47)
    at call (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:11)
    at o (frida/runtime/message-dispatcher.js:23)
```
