### ISSUE TITLE
KeyError: 'tag_name' when trying to use objection patchapk

### ISSUE THREAD

**Issue by subvert0r** [sensepost/objection#611]
Describe the bug

Objection has successfully downloaded libfrida-gadget.so, but after that it always fails to pull git tags due to network problems, but since it has successfully obtained gadget, why do I need to pull tags from github every time?

```
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    load_entry_point('objection==1.9.1', 'console_scripts', 'objection')()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/objection/console/cli.py", line 366, in patchapk
    patch_android_apk(**locals())
  File "/usr/local/lib/python3.7/site-packages/objection/commands/mobile_packages.py", line 153, in patch_android_apk
    github_version = github.get_latest_version()
  File "/usr/local/lib/python3.7/site-packages/objection/utils/patchers/github.py", line 52, in get_latest_version
    self.gadget_version = self._call(self.GITHUB_LATEST_RELEASE)['tag_name']
KeyError: 'tag_name'
```
To Reproduce

`objection patchapk -s xxx.apk
`Sometimes works fine
 
Pretty much the same as : https://github.com/sensepost/objection/issues/366

but for some unknown reason, that one was closed without any proper answer as to why is this happening

**Comment by IPMegladon** [comment]
You can skip that check by specifying the version using the `--gadget-version` flag, then it does not check in with github for a newer version. 

I think you may have missed the comment in that issue which answered how to skip this check and why it happens:
https://github.com/sensepost/objection/issues/366#issuecomment-616981867

**Comment by jkmartindale** [comment]
Documenting this in case someone else runs into the same root cause I had: the GitHub API has rate limits, which can be easier to hit if you use a VPN. In this case the rate limit error message causes a KeyError exception, and changing my IP address by disconnecting from my VPN fixed it for me.
