### ISSUE TITLE
objection explore command get ERROR on Win10 x86_64 py3.6.0

### ISSUE THREAD

**Issue by pnigos** [sensepost/objection#62]
Hi,

When i running objection.exe --gadget "com.somapp.somapp" explore i get the following error:
```
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\queues.py", line 345, in get
    return _ForkingPickler.loads(res)
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\site-packages\objection\utils\__init__.py", line 57, in <module>
    Pool(processes=1).apply_async(check_version)
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 168, in __init__
    self._repopulate_pool()
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\pool.py", line 233, in _repopulate_pool
    w.start()
  File "c:\users\pwn2own\appdata\local\programs\python\python36\lib\multiprocessing\process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```
I totally have no idea about this and googled a few times but nothing work.
Thanks!

**Comment by leonjza** [comment]
Heya,

I am not 100% sure about this one, but what I can say is that objection has not really been tested on Windows platforms. There are a few places where multiprocessing is being used. Is it possible for you to use a VM with Linux by any chance?

If anyone wants to help out with testing/PR's for Windows support then that would be awesome!

**Comment by pnigos** [comment]
Yes,no problem:)
I'll try again on Linux VM.The reason i run on Windows is because i saw this post https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/ and it run objection on Win platform so i thought it would work.

**Comment by pnigos** [comment]
P.S:Seems every objection command i run on Win10 x86_64 py3.6.x will get this error.
