### ISSUE TITLE
[bug][iOS] Crash after injecting into a specific system process

### ISSUE THREAD

**Issue by gam3-over** [sensepost/objection#628]
Hi, 

just to clarify, objections seems to work fine on my device, tried to attach to AppStore and disable ssl pinning, works flawlessly.

Now, if I try to connect to the `cloudd` process it seems the agent gets injected but it crashes here's the debug log 

`
user@users-MacBook-Pro-3  ~  objection -d -g 57160 explore

[debug] Agent path is: /opt/homebrew/lib/python3.11/site-packages/objection/agent.js
[debug] Injecting agent...
Using USB device `iPad`
[debug] Attempting to attach to process: `57160`
[debug] Process attached!
Agent injected and responds ok!
Traceback (most recent call last):
  File "/opt/homebrew/bin/objection", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/objection/console/cli.py", line 156, in explore
    device_info = get_device_info()
                  ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/objection/commands/device.py", line 27, in get_device_info
    package_info = api.env_ios()
                   ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/frida/core.py", line 491, in _rpc_request
    raise result.error
frida.core.RPCException: TypeError: cannot read property 'currentDevice' of undefined
    at <anonymous> (src/generic/environment.ts:55)
    at envIos (src/rpc/environment.ts:8)
    at apply (native)
    at <anonymous> (frida/runtime/message-dispatcher.js:13)
    at c (frida/runtime/message-dispatcher.js:23)
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
`

and here informations about that PID/process:

`57160   ??  ?Xs    0:00.00 /System/Library/PrivateFrameworks/CloudKitDaemon.framework/Support/cloudd`

Any way on how to solve it ?

**Comment by IPMegladon** [comment]
Closing as stale, however I suspect this is likely an issue in the Frida side and not objection
