### ISSUE TITLE
[bug] Unable to run objection after installation

### ISSUE THREAD

**Issue by kkeennyy-tan** [sensepost/objection#637]
**Describe the bug**
After installation of objection I got error in terminal. Kali VM was fresh install and I already used frida with my mobile

**To Reproduce**
1. sudo pip3 install objection 
2. objection -g com.bank.retail.uat explore

**Expected behavior**
Being able to explore the application

**Evidence / Logs / Screenshots**
Any output from objection, such as stack traces or errors that occurred. Be sure to run objection with the `--debug` flag so that errors from the agent are verbose enough to debug. For example:

```text
┌──(Cheesemiss㉿kali)-[~/Documents/09062023/Secured]
└─$ objection --debug explore               
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 5, in <module>
    from objection.console.cli import cli
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/console/commands.py", line 9, in <module>
    from ..commands import plugin_manager
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/commands/plugin_manager.py", line 8, in <module>
    from ..utils.plugin import Plugin as PluginType
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/utils/plugin.py", line 6, in <module>
    from ..state.api import api_state
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/state/api.py", line 1, in <module>
    from ..api.app import create_app
  File "/home/Cheesemiss/.local/lib/python3.11/site-packages/objection/api/app.py", line 1, in <module>
    from flask import Flask
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 34, in <module>
    from . import cli
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.11/dist-packages/click/core.py)

```

**Additional context**

![image](https://github.com/sensepost/objection/assets/23713619/8a166a70-035a-4741-b245-3bbc2797a847)
![image](https://github.com/sensepost/objection/assets/23713619/7727d77e-e996-4f86-8f9e-715dc5594dfc)
![image](https://github.com/sensepost/objection/assets/23713619/8e873967-2184-46b0-9ecc-2d46cd772818)
![image](https://github.com/sensepost/objection/assets/23713619/c32a61d5-6a4c-4f17-bdff-2ad711980db7)

**Comment by emonik** [comment]
I've had the same issue , upgrading "`click`" and "`black`" solved it 
```

pip3 install click --upgrade
pip3 install black --upgrade

```

**Comment by tennessine** [comment]
> I've had the same issue , upgrading "`click`" and "`black`" solved it
> 
> ```
> 
> pip3 install click --upgrade
> pip3 install black --upgrade
> ```

still the same

**Comment by tennessine** [comment]
this works for me:

https://github.com/sensepost/objection/issues/644

check the best answer there

**Comment by user243642** [comment]
I still have this issue after doing both methods.
