### ISSUE TITLE
 ios sslpinning disable - An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!

### ISSUE THREAD

**Issue by 0xarpit** [sensepost/objection#639]
Command - xxxx.iOS on (iPhone: 16.6.1) [usb] # ios sslpinning disable

Result - 

An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
script has been destroyed

Python stack trace: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/usr/local/lib/python3.11/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/usr/local/lib/python3.11/site-packages/objection/commands/ios/pinning.py", line 26, in ios_disable
    api.ios_pinning_disable(_should_be_quiet(args))
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frida/core.py", line 491, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed

**Comment by macleouc** [comment]
Hello

Have you managed to resolve this error?

I have the same problem on Android

**Comment by yangbofan** [comment]
+1
