### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anubi5egypt** [sensepost/objection#640]
Traceback (most recent call last):
  File "/home/anubi5/.local/bin/objection", line 5, in <module>
    from objection.console.cli import cli
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/console/commands.py", line 9, in <module>
    from ..commands import plugin_manager
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/commands/plugin_manager.py", line 8, in <module>
    from ..utils.plugin import Plugin as PluginType
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/utils/plugin.py", line 6, in <module>
    from ..state.api import api_state
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/state/api.py", line 1, in <module>
    from ..api.app import create_app
  File "/home/anubi5/.local/lib/python3.9/site-packages/objection/api/app.py", line 1, in <module>
    from flask import Flask
  File "/home/anubi5/.local/lib/python3.9/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/anubi5/.local/lib/python3.9/site-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/home/anubi5/.local/lib/python3.9/site-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/lib/python3/dist-packages/itsdangerous/__init__.py)
![Uploading 2023-09-27_08-06.png…]()

**Comment by anubi5egypt** [comment]
![2023-09-27_08-06](https://github.com/sensepost/objection/assets/42506882/38a6b2cd-2d4c-44ee-abb7-2f92a0b7d643)
