### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources

### ISSUE THREAD

**Issue by yanhuasanyuexyz** [sensepost/objection#644]
Microsoft Windows [版本 10.0.19045.2728]
(c) Microsoft Corporation。保留所有权利。

C:\Users\Administrator>objection
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Scripts\objection.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\console\cli.py", line 8, in <module>
    from .repl import Repl
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\console\repl.py", line 14, in <module>
    from objection.utils.agent import Agent
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\utils\__init__.py", line 7, in <module>
    from .update_checker import check_version
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\utils\update_checker.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

C:\Users\Administrator>

**Comment by Ryan-Sapone** [comment]
+1 same issue after installing frida-tools

C:\Users\MYUSER>objection
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python312\Scripts\objection.exe\__main__.py", line 4, in <module>
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\console\cli.py", line 8, in <module>
    from .repl import Repl
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\console\repl.py", line 14, in <module>
    from objection.utils.agent import Agent
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\utils\__init__.py", line 7, in <module>
    from .update_checker import check_version
  File "C:\Users\MYUSER\AppData\Local\Programs\Python\Python312\Lib\site-packages\objection\utils\update_checker.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by morellanthony** [comment]
try `pip install --force-reinstall -U setuptools`

**Comment by Ryan-Sapone** [comment]
> try `pip install --force-reinstall -U setuptools`

Thank you morellanthony - this was able to resolve the issue for me

**Comment by marcelocecin** [comment]
same error 
macOS 15.3 (24D5040f)
pip 24.3.1
Python 3.9.6

**Comment by IPMegladon** [comment]
@marcelocecin have you attempted to upgrade setuptools as mentioned in above comments?

**Comment by marcelocecin** [comment]
@IPMegladon yes, but it didn't solve it

**Comment by IPMegladon** [comment]
Should be fixed when using latest objection release
