### ISSUE TITLE
[bug] charmap codec can't decode byte 0x90  + Cant find 9patch chunk in file 

### ISSUE THREAD

**Issue by sergorl** [sensepost/objection#647]
Hello guys, I face problem with tool:
`objection patchapk --source C:\apk\app-appCenter-appPreProd-release.apk`

Log of problem:
```
c:\apk> objection patchapk --source C:\apk\app-appCenter-appPreProd-release.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 16.1.7
Patcher will be using Gadget version: 16.1.7
Detected apktool version as: 2.9.0
Running apktool empty-framework-dir...
I: Removing 1.apk framework file...
Press any key to continue . . .
Unpacking C:\apk\app-appCenter-appPreProd-release.apk
An error may have occurred while extracting the APK.
W: Cant find 9patch chunk in file: "o1.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "m3.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Tx.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "jZ.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "YM.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "rj.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "z5.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "s3.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "uW.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "51.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "h-.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Nk.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Pb.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "Hi.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "aO.9.png". Renaming it to *.png.
W: Cant find 9patch chunk in file: "sn.9.png". Renaming it to *.png.

Exception in thread Thread-10 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\sss\AppData\Local\anaconda3\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\sss\AppData\Local\anaconda3\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\sss\AppData\Local\anaconda3\lib\subprocess.py", line 1499, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\sss\AppData\Local\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 1763: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\sss\AppData\Local\anaconda3\Scripts\objection-script.py", line 33, in <module>
    sys.exit(load_entry_point('objection', 'console_scripts', 'objection')())
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\soft\0\objection\objection\console\cli.py", line 303, in patchapk
    patch_android_apk(**locals())
  File "c:\soft\0\objection\objection\commands\mobile_packages.py", line 193, in patch_android_apk
    patcher.inject_internet_permission()
  File "c:\soft\0\objection\objection\utils\patchers\android.py", line 428, in inject_internet_permission
    if internet_permission in self._get_appt_output():
  File "c:\soft\0\objection\objection\utils\patchers\android.py", line 317, in _get_appt_output
    self.aapt = o.out
  File "C:\Users\sss\AppData\Local\anaconda3\lib\site-packages\delegator.py", line 126, in out
    self.__out = self.std_out.read()
ValueError: I/O operation on closed file.
Cleaning up temp files...
```

I appreciate any recommendations of how to fix it :)

**Comment by IPMegladon** [comment]
Know this is quite long ago. 
Appears to be issue while apktool is extracting the app. You can try appending the `--skip-resources` flag. Also add `-d` for debugging before patchapk for debugging info e.g.:
` objection patchapk -d C:\apk\app-appCenter-appPreProd-release.apk --skip-resources`
