### ISSUE TITLE
[bug] Unable to run cleanups: script is destroyed

### ISSUE THREAD

**Issue by sfz009900** [sensepost/objection#651]
>objection --debug -g 24950 explore
[debug] Agent path is: c:\python39\lib\site-packages\objection\agent.js
[debug] Injecting agent...
Using USB device `Pixel 6`
[debug] Attempting to attach to process: `24950`
[debug] Process attached!
Agent injected and responds ok!
Traceback (most recent call last):
  File "C:\python39\Scripts\objection-script.py", line 33, in <module>
- [incoming message] ------------------
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "c:\python39\lib\site-packages\click\core.py", line 1157, in __call__
"process-terminated"
- [./incoming message] ----------------
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1078, in main
(session detach message) process-terminated
(process crash report)
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1688, in invoke

        *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/oriole/oriole:13/TQ1A.230205.002/9471150:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm'
Timestamp: 2023-12-17 23:14:31.162693740+0800
Process uptime: 18s
Cmdline: com.wm.motor
pid: 24950, tid: 25194, name: Thread-21  >>> com.wm.motor <<<
uid: 10250
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xae43d6d4
Abort message: 'Check failed: old_state_and_flags.GetState() != ThreadState::kRunnable (old_state_and_flags.GetState()=Runnable, ThreadState::kRunnable=Runnable) Native Thread[2,tid=25194,Runnable,Thread*=0xe50c0e10,peer=0x12d00000,"Thread-21"] Thread[2,tid=25194,Runnable,Thread*=0xe50c0e10,peer=0x12d00000,"Thread-21"]'
    r0  ae43d6d4  r1  00006788  r2  00000000  r3  00000004
    r4  00000074  r5  eb250560  r6  eb250540  r7  00000000
    r8  ae43d6ec  r9  ae43d774  r10 00012d08  r11 00000002
    ip  80000000  sp  ae43d6bc  lr  e5ad1dc3  pc  e5ac677e
backtrace:
      #00 pc 0003a77e  /apex/com.android.art/lib/libunwindstack.so (unwindstack::ElfInterfaceImpl<unwindstack::ElfTypes32>::ReadProgramHeaders(elf32_hdr const&, long long*)+202) (BuildId: f29bfabf148ca0daaf83fecdc9fc13a8)
      #01 pc 00039f43  /apex/com.android.art/lib/libunwindstack.so (unwindstack::ElfInterfaceImpl<unwindstack::ElfTypes32>::ReadAllHeaders(long long*)+70) (BuildId: f29bfabf148ca0daaf83fecdc9fc13a8)
      #02 pc 0003cf67  /apex/com.android.art/lib/libunwindstack.so (unwindstack::ElfInterfaceArm::Init(long long*)+6) (BuildId: f29bfabf148ca0daaf83fecdc9fc13a8)
      #03 pc 000384ed  /apex/com.android.art/lib/libunwindstack.so (unwindstack::Elf::Init()+48) (BuildId: f29bfabf148ca0daaf83fecdc9fc13a8)
      #04 pc 00041773  /apex/com.android.art/lib/libunwindstack.so (unwindstack::MapInfo::GetElf(std::__1::shared_ptr<unwindstack::Memory> const&, unwindstack::ArchEnum)+914) (BuildId: f29bfabf148ca0daaf83fecdc9fc13a8)
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "c:\python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\objection\console\cli.py", line 156, in explore
    device_info = get_device_info()
  File "c:\python39\lib\site-packages\objection\commands\device.py", line 41, in get_device_info
    package_info = api.env_android()
  File "c:\python39\lib\site-packages\frida\core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
  File "c:\python39\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "c:\python39\lib\site-packages\frida\core.py", line 491, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
Unable to run cleanups: script is destroyed

**Comment by sfz009900** [comment]
Has been solved, brush machine into UQ1A.231205.015 can be used normally
