### ISSUE TITLE
[bug] Getting an error 

### ISSUE THREAD

**Issue by RamkrishnaSawant** [sensepost/objection#654]
**Describe the bug**
I ran objection command I am getting below error although I have updated everything

**To Reproduce**
1. Run command 'onjection'
2. Getting below error
   Checking for a newer version of objection...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 5, in <module>
    from objection.console.cli import cli
  File "/usr/local/lib/python3.11/dist-packages/objection/console/cli.py", line 8, in <module>
    from .repl import Repl
  File "/usr/local/lib/python3.11/dist-packages/objection/console/repl.py", line 15, in <module>
    from .commands import COMMANDS
  File "/usr/local/lib/python3.11/dist-packages/objection/console/commands.py", line 9, in <module>
    from ..commands import plugin_manager
  File "/usr/local/lib/python3.11/dist-packages/objection/commands/plugin_manager.py", line 8, in <module>
    from ..utils.plugin import Plugin as PluginType
  File "/usr/local/lib/python3.11/dist-packages/objection/utils/plugin.py", line 6, in <module>
    from ..state.api import api_state
  File "/usr/local/lib/python3.11/dist-packages/objection/state/api.py", line 1, in <module>
    from ..api.app import create_app
  File "/usr/local/lib/python3.11/dist-packages/objection/api/app.py", line 1, in <module>
    from flask import Flask
  File "/usr/lib/python3/dist-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/usr/lib/python3/dist-packages/flask/app.py", line 34, in <module>
    from . import cli
  File "/usr/lib/python3/dist-packages/flask/cli.py", line 15, in <module>
    from click.core import ParameterSource
ImportError: cannot import name 'ParameterSource' from 'click.core' (/usr/local/lib/python3.11/dist-packages/click/core.py)

**Evidence / Logs / Screenshots**
![image](https://github.com/sensepost/objection/assets/96137114/0e9ebefc-dd53-497f-ad50-1c8a96ea6e5b)

**Comment by IPMegladon** [comment]
Please provide the output of `pip3 list`.

**Comment by IPMegladon** [comment]
Closing issue as stale, feel free to reopen
