### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by flamecopper** [sensepost/objection#674]
I have already run the following code backend:
root# /usr/sbin/frida-server -l 0.0.0.0:1337

 **objection -N --gadget xxxxx -h 192.168.10.119 -p 1337 explore
Using networked device @`192.168.10.119:1337`**

Using networked device @`192.168.10.119:1337`
Traceback (most recent call last):
  File "/home/alvoo/.local/bin/objection", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/home/alvoo/.local/lib/python3.11/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
              ^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/objection/utils/agent.py", line 152, in get_session
    self.session = self.device.attach(state_connection.gadget_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/alvoo/.local/lib/python3.11/site-packages/frida/core.py", line 1010, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.TransportError: timeout was reached

**Comment by flamecopper** [comment]
jammy@WW-G18RJR3:~$ objection --debug -N --gadget xyz.abc -h 192.168.10.119 -p 1337 explore
[debug] Agent path is: /home/jammy/.local/lib/python3.11/site-packages/objection/agent.js
[debug] Injecting agent...
Using networked device @`192.168.10.119:1337`
[debug] Attempting to attach to process: `xyz.abc`
[debug] Unable to find process: `xyz.abc`, attempting spawn
[debug] PID `30191` spawned, attaching...
[debug] Resuming PID `30191`
Agent injected and responds ok!
Traceback (most recent call last):
  File "/home/jammy/.local/bin/objection", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/objection/console/cli.py", line 156, in explore
    device_info = get_device_info()
                  ^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/objection/commands/device.py", line 27, in get_device_info
    package_info = api.env_ios()
                   ^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/frida/core.py", line 179, in method
    return script._rpc_request("call", js_name, args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jammy/.local/lib/python3.11/site-packages/frida/core.py", line 491, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed
Asking jobs to stop...
Unloading objection agent...
[debug] Calling unload()
Unable to run cleanups: script is destroyed

Please see another of my error when I am trying to connect via network

**Comment by KD-MM2** [comment]
try this:

on device: root# **/usr/sbin/frida-server -l 0.0.0.0**

forwarding ssh connect to mobile:
`ssh -L 27042:127.0.0.1:27042 root@192.168.0.153` 192.168.0.153 is device ip
just leave it alone then create new terminal window:

objection -N --gadget xxxxx explore
