### ISSUE TITLE
Spawn already in progress for the specified identifier

### ISSUE THREAD

**Issue by 0xtaro** [sensepost/objection#687]
I am running the latest objection on an application that is on an iPad with iPadOS 17.5.1 and I'm running Frida 16.4.7.

Using the command `objection -g [app identifier] explore` leads to the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/objection", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/objection/console/cli.py", line 114, in explore
    agent.inject()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/objection/utils/agent.py", line 202, in inject
    session = self.get_session()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/objection/utils/agent.py", line 166, in get_session
    self.spawned_pid = self.device.spawn(state_connection.gadget_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frida/core.py", line 1029, in spawn
    return self._impl.spawn(program, **kwargs)
frida.InvalidOperationError: spawn already in progress for the specified identifier
```

**Comment by IPMegladon** [comment]
Marking issue as stale, feel free to reopen.
