### ISSUE TITLE
[bug] InvalidOperationError: script has been destroyed

### ISSUE THREAD

**Issue by EvilWatermelon** [sensepost/objection#699]
**To Reproduce**
1. `objection -g app explore`
2. `ios info binary`
3. `ios keychain dump`

**Expected behavior**
Dumping the app keychain and its content to review settings

**Evidence / Logs / Screenshots**

```text
Note: You may be asked to authenticate using the devices passcode or TouchID
Save the output by adding `--json keychain.json` to this command
Dumping the iOS keychain...
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
script has been destroyed

Python stack trace: Traceback (most recent call last):
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/objection/console/repl.py", line 371, in start_repl
    self.run_command(document)
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/objection/console/repl.py", line 185, in run_command
    exec_method(arguments)
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/objection/commands/ios/keychain.py", line 79, in dump
    keychain = api.ios_keychain_list(_should_do_smart_decode(args))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/frida/core.py", line 180, in method
    return script._rpc_request(request, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/isumis/.local/pipx/venvs/objection/lib/python3.11/site-packages/frida/core.py", line 497, in _rpc_request
    raise result.error
frida.InvalidOperationError: script has been destroyed
```

**Environment (please complete the following information):**
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS 12.5.7]
 - Frida Version [e.g. current stable version]
- Objection Version [e.g. 1.11.0]

**Comment by zaidnz** [comment]
@EvilWatermelon  You found the solution yet ??

**Comment by IPMegladon** [comment]
stale
