### ISSUE TITLE
[bug] import broken in repl

### ISSUE THREAD

**Issue by rithvikvibhu** [sensepost/objection#704]
**Describe the bug**
`import <path/to/script.js>` is broken:

```
> import ~/Desktop/frida_script.js

An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'Agent' object has no attribute 'background'

Python stack trace: Traceback (most recent call last):
  File "/objection/objection/console/repl.py", line 361, in run
    self.run_command(document)
  File "/objection/objection/console/repl.py", line 169, in run_command
    exec_method(arguments)
  File "//objection/objection/commands/frida_commands.py", line 85, in load_background
    agent.background(hook)
AttributeError: 'Agent' object has no attribute 'background'
```

**To Reproduce**
1. Run command 'import anyscript.js'

**Similar issues**
None I could find when searching for "background".

**Expected behavior**
The script should load, like before.

**Evidence / Logs / Screenshots**
Stacktrace above.

**Environment (please complete the following information):**
 - Device: Android device
 - OS: Android 13
 - Frida Version: 16.5.2
- Objection Version: from git, latest master as of now (5f22e0acf7dd8fb9d3c1610629339e4fd422557d)

**Application**
Not application dependent.

**Additional context**
Looks like the background method used here:
https://github.com/sensepost/objection/blob/5f22e0acf7dd8fb9d3c1610629339e4fd422557d/objection/commands/frida_commands.py#L85

was removed from `Agent` in this commit: https://github.com/sensepost/objection/commit/865fb7dbe4a3150bfb57651157b0710ff075ed21

**Comment by IPMegladon** [comment]
Thanks, this is a known issue . I have already created a fix and changed some of the job handling to accommodate this. Though still need to clean it up a bit before I create a PR. 

In the mean time you should be able to use `evaluate ~/Desktop/frida_script.js` to load the script (you just cannot unload it).

**Comment by IPMegladon** [comment]
I have created https://github.com/sensepost/objection/pull/705 in which `import` should function as expected. Let me know if you encounter any bugs with it.
