### ISSUE TITLE
[bug] Unable to locate Objection agent sources

### ISSUE THREAD

**Issue by antoinechauvn** [sensepost/objection#707]
```python
C:\Users\XXXX>objection --serial "RZCT50FJK7D" -s -n "air.com.unit9.bkFrApp" start
Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\Scripts\objection.exe\__main__.py", line 7, in <module>
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\cli.py", line 125, in start
    agent = get_agent()
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\cli.py", line 20, in get_agent
    agent = Agent(AgentConfig(
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\utils\agent.py", line 132, in __init__
    raise Exception(f'Unable to locate Objection agent sources at: {self.agent_path}. '
Exception: Unable to locate Objection agent sources at: C:\Users\XXXX\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\agent.js. If this is a development install, check the wiki for more information on building the agent.
```

**Comment by IPMegladon** [comment]
Have you referred to https://github.com/sensepost/objection/wiki/Development-Environment-Installation ?
As the error message indicates, it does not appear the agent was compiled. Use `npm install` && `npm run build` in `agent` folder.

**Comment by IPMegladon** [comment]
Marking as stale, feel free to reopen if that did not resolve your issue.
