### ISSUE TITLE
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error:

### ISSUE THREAD

**Issue by krishnastunning** [sensepost/objection#712]
CMD i used: $ export JAVA_OPTS="-Xmx4g"
objection patchapk -s apkname.apk

objection patchapk -s jiotvs.apk
No architecture specified. Determining it using `adb`...
Detected target device architecture as: arm64-v8a
Using latest Github gadget version: 16.5.9
Patcher will be using Gadget version: 16.5.9
Detected apktool version as: 2.10.0
Running apktool empty-framework-dir...
I: Removing 1.apk framework file...
Unpacking jiotvs.apk
App already has android.permission.INTERNET
Target class not specified, searching for launchable activity instead...
Unable to determine the launchable activity using aapt, trying to manually parse the AndroidManifest for activity aliases...
Smali not found in smali directory. This might be a multidex APK. Searching...
Found smali at: /tmp/tmpj_fay3i_.apktemp/smali_classes7/com/jio/media/tv/ui/permission_onboarding/PermissionActivity.smali
Reading smali from: /tmp/tmpj_fay3i_.apktemp/smali_classes7/com/jio/media/tv/ui/permission_onboarding/PermissionActivity.smali
Injecting loadLibrary call at line: 225
Attempting to fix the constructors .locals count
Current locals value is 0, updating to 1:
Writing patched smali back to: /tmp/tmpj_fay3i_.apktemp/smali_classes7/com/jio/media/tv/ui/permission_onboarding/PermissionActivity.smali
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error:

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at brut.androlib.ApkBuilder.build(SourceFile:0)
        at brut.apktool.Main.main(SourceFile:0)
Caused by: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        ... 2 more
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3745)
        at java.base/sun.nio.fs.UnixPath.encode(UnixPath.java:152)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.io.File.toPath(File.java:2329)
        at brut.androlib.src.SmaliBuilder.buildFile(SourceFile)
        at brut.androlib.ApkBuilder.buildSourcesSmali(SourceFile:0)
        at brut.androlib.ApkBuilder.scheduleDexBuild(SourceFile)
        at brut.androlib.ApkBuilder.lambda$scheduleBuildDexFiles$1(SourceFile)
        at brut.androlib.ApkBuilder$$Lambda$43/0x0000000840079c40.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

Built new APK with injected loadLibrary and frida-gadget
Performing zipalign
Zipaligning the APK may have failed. Read the following output to determine if zipalign actually had an error:

W/zip     (  775): WARNING: header mismatch
W/zip     (  775): WARNING: header mismatch
W/zip     (  775): WARNING: header mismatch
W/zip     (  775): WARNING: header mismatch

Zipalign completed
Signing new APK.
Signed the new APK
Copying final apk from /tmp/tmpj_fay3i_.apktemp.aligned.objection.apk to jiotvs.objection.apk in current directory...
Cleaning up temp files...
![Screenshot 2024-12-23 135256](https://github.com/user-attachments/assets/454898ab-9efb-402d-8b08-f3beb1c4540d)

**Comment by IPMegladon** [comment]
This is not an objection issue but rather related to apktool. I recommend directly trying to extract and rebuild the application using apktool without making any changes to narrow down the issue. Also recommend looking at similar issues people have had in the past: https://github.com/iBotPeaches/Apktool/issues?q=java.lang.OutOfMemoryError
