### ISSUE TITLE
Error with Tencent packed apk

### ISSUE THREAD

**Issue by PierrickP** [sensepost/objection#72]
I get an error with a tencent packed apk

```console
root@foo:~# objection patchapk --source oBike_v3.3.1_apkpure.com.apk -a arm64-v8a -V 10.7.7 -k    
Using manually specified version: 10.7.7
Patcher will be using Gadget version: 10.7.7
Unpacking oBike_v3.3.1_apkpure.com.apk
App already has android.permission.INTERNET
Smali not found in smali directory. This might be a multidex APK. Searching...
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 9, in <module>
    load_entry_point('objection==1.2.8', 'console_scripts', 'objection')()
  File "/home/pierrick/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pierrick/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pierrick/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pierrick/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pierrick/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pierrick/.local/lib/python3.5/site-packages/objection/console/cli.py", line 241, in patchapk
    patch_android_apk(**locals())
  File "/home/pierrick/.local/lib/python3.5/site-packages/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library()
  File "/home/pierrick/.local/lib/python3.5/site-packages/objection/utils/patchers/android.py", line 552, in inject_load_library
    raise Exception('Unable to find smali to patch!')
Exception: Unable to find smali to patch!
Not cleaning up temporary files
```
test with apkid

```console
root@foo:~# ./apkid.sh /home/pierrick/works/obike/oBike_v3.3.1_apkpure.com.apk 
[+] APKiD 1.0.0 :: from RedNaga :: rednaga.io
[*] oBike_v3.3.1_apkpure.com.apk
 |-> packer : Tencent
[*] oBike_v3.3.1_apkpure.com.apk!classes.dex
 |-> anti_vm : Build.BOARD check, Build.FINGERPRINT check, Build.HARDWARE check, Build.MANUFACTURER check, Build.MODEL check, Build.PRODUCT check, Build.TAGS check, network operator name check, possible Build.SERIAL check, possible ro.secure check, subscriber ID check
 |-> compiler : dexlib 2.x
```

How can i patch this apk ? 
Can it works if i use the frida app on root ?

**Comment by leonjza** [comment]
Hey, unfortunately I don't think objection will be able to patch in a Frida gadget for you when packed like that. Best bet would be to load `frida-server` onto a rooted device and using it as specified in the documentation [here](https://github.com/sensepost/objection/wiki/Running-On-A-Rooted-Device).

Good luck!

**Comment by PierrickP** [comment]
@leonjza  yeah i agree, it's out of scope.
Thanks you anyway
