### ISSUE TITLE
objection patchapk error - Debian

### ISSUE THREAD

**Issue by Simon-Davies** [sensepost/objection#73]
See console output below:

```
si@android:~$ objection patchapk --source /home/si/app-debugNotObfuscated.apk --architecture x86
Using latest Github gadget version: 10.7.7
Patcher will be using Gadget version: 10.7.7
Unpacking /home/si/app-debugNotObfuscated.apk
An error may have occured while extracting the APK.
Exception in thread "main" java.lang.NullPointerException
	at brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleValue.java:58)
	at brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java:516)
	at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
	at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
	at brut.apktool.Main.cmdDecode(Main.java:166)
	at brut.apktool.Main.main(Main.java:81)

App already has android.permission.INTERNET
Smali not found in smali directory. This might be a multidex APK. Searching...
Traceback (most recent call last):
  File "/home/si/.local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/home/si/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/si/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/si/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/si/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/si/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/si/.local/lib/python3.5/site-packages/objection/console/cli.py", line 241, in patchapk
    patch_android_apk(**locals())
  File "/home/si/.local/lib/python3.5/site-packages/objection/commands/mobile_packages.py", line 161, in patch_android_apk
    patcher.inject_load_library()
  File "/home/si/.local/lib/python3.5/site-packages/objection/utils/patchers/android.py", line 552, in inject_load_library
    raise Exception('Unable to find smali to patch!')
Exception: Unable to find smali to patch!
Cleaning up temp files...
Failed to cleanup with error: [Errno 2] No such file or directory: '/tmp/tmpbi93vjw0.apktemp.objection.apk'
```

**Comment by leonjza** [comment]
Can you extract this app with `apktool` ?

**Comment by Simon-Davies** [comment]
I can extract the apk with:

apktool d -f -o  /home/si/app /home/si/app-debugNotObfuscated.apk

**Comment by leonjza** [comment]
Alright. I would need help debugging this one then. Is it possible for you to have a closer look? Thanks!

**Comment by Simon-Davies** [comment]
Do you want me to send you certain log files? What do you mean by a closer look?

**Comment by leonjza** [comment]
You need to inspect the source code to try and get an idea of why the patcher may have failed. You can add the `-k` flag to skip the cleanup operations as the script end so that you can investigate the resultant smali that is produced when `apktool` has finished its run. Based on the output you have sent, either the `apktool` extract is not happy (maybe a flag) or there simply isn't logic to find the launcher activity (which is why you need to investigate the smali).

**Comment by Simon-Davies** [comment]
I tried adding --decode-resources after --architecture but it is saying --decode-resources isn't an option. 

I'm using the latest version of Objection 1.2.8

**Comment by leonjza** [comment]
Try `--skip-resources`. Adding `--help` to any command will give you the available options.

**Comment by Simon-Davies** [comment]
I tried with goatdroid.apk and that worked perfectly.

I then tried with my apk and this is the Console output:
```

objection patchapk --source /home/si/app-debugNotObfuscated.apk --architecture x86 --skip-resources
Using latest Github gadget version: 10.7.7
Patcher will be using Gadget version: 10.7.7
Unpacking /home/si/app-debugNotObfuscated.apk
App already has android.permission.INTERNET
Reading smali from: /tmp/tmpxm_5ayl0.apktemp/smali/com/***/***/***.smali
Injecting into an existing constructor
Injecting loadLibrary call at line: 22
Writing patched smali back to: /tmp/tmpxm_5ayl0.apktemp/smali/com/***/***/***.smali
Creating library path: /tmp/tmpxm_5ayl0.apktemp/lib/x86
Copying Frida gadget to libs path...
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

[Fatal Error] AndroidManifest.xml:1:1: Content is not allowed in prolog.

Built new APK with injected loadLibrary and frida-gadget
Signing new APK.
Signing the new APK may have failed.
jarsigner: unable to sign jar: no response from the Timestamping Authority. When connecting from behind a firewall an HTTP or HTTPS proxy may need to be specified. Supply the following options to jarsigner:
  -J-Dhttp.proxyHost=<hostname>
  -J-Dhttp.proxyPort=<portnumber>
or
  -J-Dhttps.proxyHost=<hostname> 
  -J-Dhttps.proxyPort=<portnumber> 


Signed the new APK
Performing zipalign
Zipaling completed
Copying final apk from /tmp/tmpxm_5ayl0.apktemp.aligned.objection.apk to /home/si/app-debugNotObfuscated.objection.apk in current directory...
Cleaning up temp files...
```

**Comment by leonjza** [comment]
Skipping resource decoding can result in the error you are seeing, hence why its optional. The Timestamping issue seems network related.

**Comment by Simon-Davies** [comment]
Does that mean it worked this time with --skip-resources ?

**Comment by leonjza** [comment]
No.

**Comment by Simon-Davies** [comment]
It seems to be working fine after adding skip-resources. I could connect to the patched apk with objection explore. Thank you for all your help.
