### ISSUE TITLE
disable ssl pinning not work

### ISSUE THREAD

**Issue by HamidZaeri** [sensepost/objection#76]
Hi
I did everything but the app say cannot connect to server!

> Using fiddler + MEmu 5.2.3 + https://play.google.com/store/apps/details?id=com.bpm.sekeh&hl=en

```
PS C:\Users\Hamid\AppData\Local\Programs\Python\Python36-32\Scripts> .\objection --gadget "com.bpm.sekeh" explore
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 108, in worker
    task = get()
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\site-packages\objection\utils\__init__.py", line 57, in <module>
    Pool(processes=1).apply_async(check_version)
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "c:\users\hamid\appdata\local\programs\python\python36-32\lib\multiprocessing\process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children

     _     _         _   _
 ___| |_  |_|___ ___| |_|_|___ ___
| . | . | | | -_|  _|  _| | . |   |
|___|___|_| |___|___|_| |_|___|_|_|
        |___|(object)inject(ion) v1.2.8

     Runtime Mobile Exploration
        by: @leonjza from @sensepost

[tab] for command suggestions
com.bpm.sekeh on (Samsung: 5.1.1) [usb] # android hooking search classes TrustManager
android.net.http.X509TrustManagerExtensions
com.android.org.conscrypt.TrustManagerFactoryImpl
javax.net.ssl.X509TrustManager
javax.net.ssl.TrustManagerFactory
com.android.org.conscrypt.TrustManagerImpl$ExtendedKeyUsagePKIXCertPathChecker
javax.net.ssl.TrustManagerFactorySpi
[Ljavax.net.ssl.TrustManager;
javax.net.ssl.TrustManager
com.android.org.conscrypt.TrustManagerImpl

Found 9 classes
com.bpm.sekeh on (Samsung: 5.1.1) [usb] # android sslpinning disable
Job: cc10d50a-a611-451f-ac19-4663fe60a075 - Starting
[4663fe60a075] [android-ssl-pinning-bypass] Custom, Empty TrustManager ready
[4663fe60a075] [android-ssl-pinning-bypass] TrustManagerImpl
Job: cc10d50a-a611-451f-ac19-4663fe60a075 - Started
com.bpm.sekeh on (Samsung: 5.1.1) [usb] # [4663fe60a075] [android-ssl-pinning-bypass] Overriding SSLContext.init() with the custom TrustManager
[4663fe60a075] [android-ssl-pinning-bypass] Overriding SSLContext.init() with the custom TrustManager
[4663fe60a075] [android-ssl-pinning-bypass] Overriding SSLContext.init() with the custom TrustManager
[4663fe60a075] [android-ssl-pinning-bypass] Overriding SSLContext.init() with the custom TrustManager
```

Insert this number in the first step to check if the app working (connecting);

> 09312233445

I have tried JustTrustMe before and did not work too

**Comment by HamidZaeri** [comment]
Thanks,
1. Is there any app or script to help find that method?

2. Any other way to see http I/o without touching ssl (mitm)? (Like on the app itself)

**Comment by leonjza** [comment]
If no tooling works then only manual reverse engineering efforts will help you from there onwards. You can start by decompiling the app and taking a closer look at the insides and taking it from there.

**Comment by HamidZaeri** [comment]
I meant any other tool to help with finding that ssl function in smali codes.
It's hard to search all of them with try and error!

**Comment by aydintt** [comment]
please let me know if anyone can bypass this app. The cost will be paid.
