### ISSUE TITLE
Error in rebuilding APK

### ISSUE THREAD

**Issue by H0nus** [sensepost/objection#96]
I got this error during the recompiling of application.
```
Rebuilding the APK with the frida-gadget loaded...
Rebuilding the APK may have failed. Read the following output to determine if apktool actually had an error: 

Exception in thread "main" java.lang.NoSuchMethodError: brut.androlib.meta.StringExConstructor.constructScalar(Lorg/yaml/snakeyaml/nodes/ScalarNode;)Ljava/lang/Object;
	at brut.androlib.meta.StringExConstructor.access$100(StringExConstructor.java:25)
	at brut.androlib.meta.StringExConstructor$ConstructStringEx.construct(StringExConstructor.java:32)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:85)
	at org.yaml.snakeyaml.constructor.SafeConstructor.flattenMapping(SafeConstructor.java:70)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:190)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
	at brut.androlib.meta.MetaInfo.load(MetaInfo.java:70)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:260)
	at brut.androlib.Androlib.build(Androlib.java:274)
	at brut.androlib.Androlib.build(Androlib.java:267)
	at brut.apktool.Main.cmdBuild(Main.java:238)
	at brut.apktool.Main.main(Main.java:76)
```

**Comment by leonjza** [comment]
Unfortunately this error contains no information about the actual problem, other than the fact that `apktool` couldn't rebuild the app. I suggest you try to manually unpack the target application with `apktool d` and then repack it to see if that succeeds. If it doesn't, the stack trace should contain some information for you about why. Depending on your target, you could consider the `-no-res` flag as well, but this does not always work out. That flag is set with the `--skip-resources` flag in `objection` and passed on to `apktool` if set.

**Comment by H0nus** [comment]
Ok, I'm going to test and update you
PS: this error happens with all kinds of apps. So maybe is apktool's problem?

**Comment by H0nus** [comment]
Actually fixed by downloading the jar file from releases of apktool repository (version 2.3.3) and purging the one downloaded from Ubuntu's repo (version 2.3.3-dirty).
Thanks for the advices!
