### ISSUE TITLE
objection crashing app

### ISSUE THREAD

**Issue by bensh** [sensepost/objection#99]
Frida 11.0.13 - iOS 9.0.2 - jailbroken

Although looking likely to be a Frida issue?

$ objection --gadget "Client" explore
Traceback (most recent call last):
  File "/usr/local/bin/objection", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/objection/console/cli.py", line 90, in explore
    device_info = get_device_info()
  File "/usr/local/lib/python3.7/site-packages/objection/commands/device.py", line 20, in get_device_info
    runner.run(hook=hook)
  File "/usr/local/lib/python3.7/site-packages/objection/utils/frida_transport.py", line 350, in run
    session = self.get_session()
  File "/usr/local/lib/python3.7/site-packages/objection/utils/frida_transport.py", line 285, in get_session
    return device.attach(state_connection.gadget_name)
  File "/usr/local/lib/python3.7/site-packages/frida/core.py", line 108, in attach
    return Session(self._impl.attach(self._pid_of(target)))
frida.ProcessNotRespondingError: expecting to read a single byte for receiving credentials but read zero bytes

**Comment by leonjza** [comment]
I have seen someone in the Frida IRC report a similar issue with exactly the same error. You can try and attach just Frida to your process to test with as well, and possible make a bug report there.

**Comment by bensh** [comment]
Posted a bug in the Frida github, here for completeness.
https://github.com/frida/frida/issues/543

**Comment by leonjza** [comment]
Frida has had a few updates since this issue was reported. Please update and test.
